### ISSUE TITLE
[Question] Why Box should be used to insert elements into a linked list?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#118]
I am wondering why Box should be used to insert elements into a linked list.

I concluded that without Box, the element data which are stored in the stack cannot direct to each other because the node size cannot be calculated. And Box can solve this because they are smart pointers so that rust doesn't care about where Box points to. 

With clarification and a more detailed explanation, I would be very grateful.

**Comment by tomtomjhj** [comment]
`Box::new(x)` is basically `malloc(sizeof(x))` + moving the (ownership of) `x` to the allocated heap memory block from the stack.

> the element data which are stored in the stack cannot direct to each other because the node size cannot be calculated

It's not impossible to do that and the node size isn't relevant here.

```rust
pub fn so_wow(elt1: T, elt2: T) -> Self {
    let mut node1 = Node::new(elt1);
    let mut node2 = Node::new(elt2);
    let node1_ptr = &mut node1 as *mut _;
    let node2_ptr = &mut node2 as *mut _;
    node1.next = node2_ptr;
    node2.prev = node1_ptr;
    LinkedList {
        head: node1_ptr,
        tail: node2_ptr,
        len: 2,
        marker: PhantomData,
    }
}

```
However, in most cases it just makes much more sense to link the nodes after moving them to the heap.
For example, `so_wow` itself is not marked `unsafe` itself, but it's actually incredibly unsafe.

Quiz: what could go wrong when the `LinkedList` returned by `so_wow` is `drop`ped?

**Comment by integerblue** [comment]
I guess that the ownership of node1 and node2 belongs to so_wow so that when so_wow is dropped, node1_ptr and node2_ptr could be invalidated. Then how could we move the ownership to the LinkedList? Rather than using a pointer, should we use just a node inside it?

**Comment by tomtomjhj** [comment]
LinkedList behave as if it has the ownerships of nodes. But this ownership can't be expressed in a way that rustc can understand and check (we are using raw pointers). 

If you insert a node that is still on stack into the LinkedList, than there will be 2 parties that assert the ownership of the node (the function that has the node in its stack and the LinkedList). That's why we move the node from stack to heap using Box.

**Comment by integerblue** [comment]
You mean so_wow and LinkedList?
I ubderstood as so_wow created the Node in its stack so it has the ownership and LinkedList which has pointer in it and behaves likr it has the ownership.
But it seems that so _wow is finished after returning LinkedList to the caller, so Node seems to be dropped at the end of its lifetime. why isn't?

**Comment by tomtomjhj** [comment]
> I understood as so_wow created the Node in its stack so it has the ownership and LinkedList which has pointer in it and behaves like it has the ownership.

Correct

> But it seems that so _wow is finished after returning LinkedList to the caller, so Node seems to be dropped at the end of its lifetime. why isn't?

The node indeed gets dropped when `so_wow` returns. The problem is that (1) the node gets dropped again when the LinkedList gets dropped. Even worse, (2) it will try to `free()` the pointer to the stack.

So we have to (2) move the node to the heap using `Box::new` and (1) prevent it from getting dropped using `Box::into_raw` (wrapper of `Box::leak`).
