### ISSUE TITLE
[Question] Property of take()

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#121]
In  #102, I had an issue with that `join()` in `drop()` for workers got hanged, and many people had different good suggestions, but none of them worked. Apparently, the problem was with dropping the sender. When dropping sender in `Threadpool::drop`, I didn't used `take()` but opted for `match` on `self.job_sender`, and had something like `Some(s) => drop(s)`. This resulted in a hang. I tried again with `take()`, and this time it executed properly. This got me asking the question what is the key difference between the two implementations, as I thought that `match` on the sender is doing the same thing. What was the problem?

**Comment by tomtomjhj** [comment]
If you do `Some(s) => drop(s)` you will probably get a compiler error that says you can't "move out of" something because it's behind a reference. My guess is that you probably tried to fix that error by doing `Some(ref s) => drop(s)` which effectively does nothing because `s` here is of type <code><strong>&</strong>Sender\<Job></code>, not `Sender<Job>`.

**Comment by tomtomjhj** [comment]
Then the remaining questions are
1. Why can I not "move out of" something?
2. How does `Option::take` work?
, which I encourage you to answer yourself.

**Comment by Lee-Janggun** [comment]
`match`is what I did wrong. Thank you very much for the detailed answer!
