### ISSUE TITLE
[Question] Interpretation of job_count

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#123]
I have `Theradpool` working except for `thread_pool_join_block`, and so I looked at [#85(comment)](https://github.com/kaist-cp/cs492-concur/issues/85#issuecomment-696888546). It mentioned that there are more than one interpretations of `job_count`, but I could not think of one other than number of times `Threadpool::execute` that is currently running. Is this the correct interpretation?

Also, I think that if there is such ambiguity in interpretation of variables, such should be eliminated in the future. I do not think it is fair for us to spend time in the wrong direction due to incorrect interpretation that could be avoided.

**Comment by tomtomjhj** [comment]
I think there is a better approach for fixing that. Instead of trying to find another interpretation of the name `job_count`, I recommend you to construct a concrete counterexample in which your implementation violates the condition of the test. You can think of an interleaving of the commands run by each thread.
