### ISSUE TITLE
[Question] Does the drop method automatically run even if we implemented the drop trait manually?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#125]
I am curious whether the basic drop method implemented in rust classes runs even if we implemented the drop trait manually.

If we implement the drop trait by ourselves like in HW1, then the drop method is automatically called when the lifetime of the instance ended. But we didn't implement how to free memory or clean up things. Does rust care about those things even if we overwrite the drop trait with our own? Also, if we manually call the mem::drop, does rust automatically calls the drop method at the end of the lifetime?

**Comment by tomtomjhj** [comment]
When a variable reaches it end of life, its destructor is run automatically. The destructor of `T` consists of 2 stages:
1. run `<T as Drop>::drop` if `T` manually implements `Drop` 
2. if `T` contains fields, then run recursively run their destructor

After that, the region of stack where that variable resided will be reclaimed by popping the stack.

What about `free()`? In [this comment](https://github.com/kaist-cp/cs492-concur/issues/118#issuecomment-705625609) I mentioned that `Box::new` is basically `malloc` + α. Symmetrically, `<Box<T> as Drop>::drop` is basically calling `free()` on the pointer the box owned. (This is [hardwired into the compiler](https://doc.rust-lang.org/src/alloc/boxed.rs.html#543-547).) This is why we use `Box::from_raw` in methods like `pop_front_node`.


The implementation of `mem::drop` is surprisingly simple:
```rust
pub fn drop<T>(_x: T) {}
```
It simply ends the lifetime of `_x` so that its destructor is run.

**Comment by tomtomjhj** [comment]
>  This is why we use Box::from_raw in methods like pop_front_node 

More specifically, `pop_front` runs `Node::into_element` on the result of `pop_front_node` which:
1. takes the ownership of `Box<Node<T>>`;
2. derefences the box, which is also [hardwired into the compiler](https://doc.rust-lang.org/stable/reference/special-types-and-traits.html#boxt) so that it moves the content of the box from heap to a temporary location and free the heap memory block;
3. out of 3 fields `next`, `prev`, and `element`, returns the `element` in the temporary to the caller;
4. and run the destructors for `next` and `prev` because then went out of the scope (they do nothing because they are raw pointers, which are `Copy`).

**Comment by YujinGaya** [comment]
[std::ops::Drop trait documentation](https://doc.rust-lang.org/std/ops/trait.Drop.html) and [the reference on destructor](https://doc.rust-lang.org/reference/destructors.html) might help you get the comprehensive view on how destructor works in Rust.
