### ISSUE TITLE
[Question] java causality test case 7

### ISSUE THREAD

**Issue by castlecowrice** [kaist-cp/cs492-concur#130]
I would like to know whether I've understood the promising semantics correctly. Below is my thought process about causality test case 7.

1. Thread 2 promises x = 1 because it can always write x = 1 in the future.
2. Thread 1 promises y = 1 because it can read x = 1 and then write that value 1 to y(?). Since Thread 1 read x = 1 while promising, the view of Thread 1 is moved to x = 1(?). Also, the promise that Thread 1 makes will have higher timestamp value than the promise that Thread 1 has made, because it was promised later(?).
3. Thread 2 is executed. It will read y = 1, store z = 1, and finally it will fulfill the promise x = 1. Re-certification always succeeds.
4. Thread 1 is executed. It will read z = 1, x = 1, and finally it will fulfill the promise y = 1. Re-certification always succeeds.

I would appreciate it if you tell me in which part I was correct or wrong. Especially I'm curious whether I thought correctly on some parts marked with (?).

**Comment by jeehoonkang** [comment]
1. Right.

1. Not quite right.  Thread 1's view is not advanced in the normal execution because the view is advanced in certification, which is just for checking if a promise is possible or not.  Right after promising to write y=1, your view is still at @0 for all locations.  Also, the timestamps of x=1 and y=1 messages are incomparable because they're writing to different locations.

1. Right.

1. Right.

**Comment by castlecowrice** [comment]
As I remember, the certification occurs right after it promises. So the view of thread 1 is moved to x = 1 during that certification, right? If not, does the move occurs while thread 1 actually executes r2 = x?

**Comment by jeehoonkang** [comment]
After a promise is certified, your view is restored to the original view right before promising to write a message.  So thread 1's view is back to point to X=0.
