### ISSUE TITLE
[Question] What makes the Java causality test cases 16, 19 & 20 wrong?

### ISSUE THREAD

**Issue by gunwooterry** [kaist-cp/cs492-concur#131]
In class, you mentioned that test cases 16, 19 and 20 are now proven to be wrong.
Could you please explain why? I think we haven't covered the case that joins a thread.

Below are the test cases:

### Causality test case 16
```
Initially, x = 0

Thread 1:
r1 = x
x = 1

Thread 2:
r2 = x 
x = 2

Behavior in question: r1 == 2; r2 == 1

Decision: Allowed.
```

### Causality test case 19
```
Initially,  x = y = 0

Thread 1:
join thread 3
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Thread 3:
r3 = x
if (r3 != 42)
  x = 42

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. This is the same as test case 17, except that thread 1 has been split into two threads.
Causality test case 20
Initially,  x = y = 0
```

### Causality test case 20
```
Thread 1:
join thread 3
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Thread 3:
r3 = x
if (r3 == 0)
  x = 42

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. This is the same as test case 18, except that thread 1 has been split into two threads.
```

**Comment by jeehoonkang** [comment]
- Test case 16: it's forbidden.  without loss of generality, let's assume x=1 is placed before x=2 in the memory.  Then it's impossible for thread 1 to read x=2 and then write x=1.

- Test case 19/20: it's forbidden.  Roughly speaking, the y=42 message by thread 1 cannot be promised because it requires cooperation of thread 3.  Note that it was possible in the test case 17/18 because thread 1 and 3 are the same threads.
