### ISSUE TITLE
Promising semantics - execution order

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#135]
Thread 1        Thread 2
 instruction1 || instruction3
 instruction2 || instruction4

If we want to disprove certain behavior from the above case (using promising semantics),
I think we should inspect all possible cases.

By 'all possible cases', I have a question
: **'In promising semantics', is it enough to only inspect the following 'execution' order : instruction1-2-3-4 ?**

What I meant by this is that,
in promising semantics, it seems like different behaviors from thread interleaving is covered by 'view's. In result, doing promising semantic in the order of instruction 1-2-3-4 is the same as doing in any other orders (like instruction 1-3-4-2 ,...).

**Comment by TonyWild** [comment]
I believe that in those examples in the lecture, executing 3 before 2 won't proceed for thread 2 so those cases are disregarded. But in general, I guess we have to consider all the cases of thread interleaving too.

**Comment by AnHaechan** [comment]
But I feel like different possibilities arise from thread interleaving is already covered by 
different possibilities when we're changing per-thread view.
Like when thread1's view is at (X, time:0) and at location X, values are (0, time:0) , (1,time:1) 
then  load(X) in thread1 has two possibilities. 
In my gut feeling, these possibilities covers different thread interleaving.

**Comment by jeehoonkang** [comment]
- No, you have to all possible combinations in general: 1-2-3-4, 1-2-4-3, 1-3-2-4, 1-3-4-2, ..., 4-3-2-1 (4! cases).  Even in a case, there may be multiple subcases depending on the value read by a load instruction.  Also, some cases may be impossible because loads are not speculated and stores are speculated (promised) only when certified.

- For example, consider the following example: "r1 = fetch-add(X, 1) || r2 = fetch-add(X, 1)".  The values of (r1,r2) depend on the execution order.

**Comment by AnHaechan** [comment]
If I have to consider all the reordering cases,
how should I do in the following case?

X=1 || r1=X;r2=X [r1=1, r2=0 possible?]

It was pretty easy to show r1=1,r2=0 is not allowed if I just do promising semantic in the order of X=1 -> r1=X -> r2=X.
However, if I consider a reordered case like r2=X->X=1->r1=X, [r1=1,r2=0] is possible.
So I guess that I have to use a knowledge "r1=X;r2=X cannot be reordered".
Then, is promising semantics really 'modelling' relaxed behavior? I got confused .

**Comment by jeehoonkang** [comment]
- For the example above, r1=X and r2=X are not reordered because r2=X is a load, which is not promised.
- The promising semantics is indeed modeling relaxed behaviors.  If you're still confused, please ask questions with examples so that I can explain them to you.

**Comment by AnHaechan** [comment]
1.
r1=X ;  Y=r1 ||  r2=Y; X=1

In the lecture, in order to prove that [r1=r2=1 is allowed] in this case,
we first certified the promise for X.store(1).
But **why** did we certified the promise for **X.store(1)**?

How can we choose which promise to certify in general sense?

2.
r1=X; Y=r1 || r2=Y; X=r2 
In the lecture, to show [r1=r2=1 is not allowed], we just show promise for store 1 at X is not certified. 
(1) To strictly prove that [r1=r2=1 is not allowed], 
then should we consider all possible reordering cases?
(2) Then what is the process of choosing possible reordering cases?
   Isn't the role of promise is to model the store hoisting? Hence, is it necessary to consider
   store-hoisted (reordered) case separately in promising semantics?

Thanks.

**Comment by integerblue** [comment]
1. I think we should choose the promise which is executed always. If there are many, we should consider each one of them to get the desired behaviors. 

2. (1) There are no ways to promise X or Y to be 1 so that we cannot get 1 out of the thin air. I think this could be enough explanation for that.
(2) I think we should consider all of them. Promising semantics is a model to represent the store hoisting like you said, in a clearer way.

**Comment by jeehoonkang** [comment]
1. I agree with @integerblue : promising to write X=1 is one of the possible choices, and it leads us to the desired behavior.

1. (1) yes.  (2) for the example, I implicitly classified all the executions with the first instruction to execute.  Since the two threads are symmetric, we can only consider the first thread's instructions without loss of generality.  Now if we execute the first instruction (r1=X) first, then we don't get the desired behavior.  If we try to promise the second instruction (Y=r1), the only value we can promise is Y=0, which also doesn't lead us to the desired behavior.  Above is the complete analysis of the all possible reorderings/behaviors.

**Comment by AnHaechan** [comment]
I have a few more questions about possible execution orders.
 
{X=0, Y=0} X=1 || Y=1;Y=2 {Y=1 disallowed}

First, showing disallowed -> consider all possible cases.
By all possible cases, it is determined by (1) reordering in a thread (2) interleaving bt. threads

(1) reordering in a thread 
T1 : X=1, single instruction
T2:  Y=1;Y=2
-> since Y=2 is 'store' to shared mem.loc. , 
it can be reordered **--> this doesn't mean considering execution order of promising semantic as Y=2->Y=1, but consider "promise for Y=2" exist. **

(2) interleaving bt. threads (*in this case, there's no shared memory location so interleaving of threads will not matter but to show general solving algorithm)

By (1), six cases are possible: 
T1.1 -> T2.1 -> T2.2 (w/o promise store(Y,1))
T2.1 -> T1.1 -> T2.2 (w/o promise store(Y,1))
T2.1 -> T2.2 -> T1.1 (w/o promise store(Y,1))
T1.1 -> T2.1 -> T2.2 (w/ promise store(Y,1))
T2.1 -> T1.1 -> T2.2 (w/ promise store(Y,1))
T2.1 -> T2.2 -> T1.1 (w/ promise store(Y,1))

show for each case, {Y=1} never happens.

Of course, if we use prior knowledge 'Y=1;Y=2 never reordered because of WW coherence' then the prove of behavior will be trivial.
But, in the lecture, what we showed was
{X=0}X=1;X=2{X=1} is not allowed (i.e. WW coherence holds) **using our promising semantics' rules** .
Not using knowledge 'WW reordering is not allowed' to prove behaviors using promising semantics.

**Comment by jeehoonkang** [comment]
- > Now if we execute the first instruction (r1=X) first,

  It means, among all possible reorderings, we're considering such reorderings for which r1=X is executed first.  So we don't need to consider interleaving among multiple threads from there on.  Notice the previous sentence: without loss of generality, we're assuming thread 1 executes first.

- Even though Y=2 can be promised, its timestamp must be greater than Y=1's timestamp.  As a result, at the end of the day, the latest value stored in the memory must be Y=2.

- Yes, proving a certain behavior is disallowed, requires much more efforts.  It's natural because of the inherent nondeterminism of concurrency.  To prove a certain behavior is possible, you can choose one execution among many; on the other hand, to prove a certain behavior is impossible, you must consider **all** executions.

**Comment by AnHaechan** [comment]
@jeehoonkang  Thanks a lot! BTW, if you have enough time, can you answer this[https://github.com/kaist-cp/cs492-concur/issues/137](url) new question, too?
