### ISSUE TITLE
[Question] Java Causality Case 14, 17, 18

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#136]
```
Causality test case 14
Initially, a = b = y = 0, y is volatile

Thread 1:
r1 = a
if (r1 == 0)
  y = 1
else
  b = 1

Thread 2:
do {
  r2 = y
  r3 = b
  } while (r2 + r3 == 0);
a = 1;

Behavior in question: r1 == r3 = 1; r2 = 0

Decision: Disallowed In all sequentially consistent executions, r1 = 0 and
	the program is correctly synchronized. Since the program is correctly
	synchronized in all SC executions, no non-sc behaviors are allowed.
```
```
Causality test case 17
Initially,  x = y = 0

Thread 1:
r3 = x
if (r3 != 42)
  x = 42
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. A compiler could determine that at r1 = x in thread 1,
  is must be legal for to read x and see the value 42. Changing r1 = x 
  to r1 = 42 would allow y = r1 to be transformed to y = 42 and performed
  earlier, resulting in the behavior in question.
```
```
Causality test case 18
Initially,  x = y = 0

Thread 1:
r3 = x
if (r3 == 0)
  x = 42
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. A compiler could determine that the only legal values
  for x are 0 and 42. From that, the compiler could deduce that r3 != 0 implies
  r3 = 42.  A compiler could then determine that at r1 = x in thread 1,
  is must be legal for to read x and see the value 42. Changing r1 = x 
  to r1 = 42 would allow y = r1 to be transformed to y = 42 and performed
  earlier, resulting in the behavior in question.
```

In test case 14, It seems that 'y' is volatile so that the compiler cannot optimize the do while the code with a=1 in thread 2. However, in promising semantics, I think a = 1 is always executed so that it could be certified. How could we interpret this 'volatile' in promising semantics?

In test case 17, thread 1 can certify y as 42 because x is always 42, and it could be recertified after the execution of thread 2. However, when I tried to certify x as 42 in thread 1, it is impossible to recertify it because r3 is not 0, and recertification with x = 42 fails. In the same manner, x cannot be recertified as 42 in test case 18. Can I just certify y as 42? It seems that x is always 42 so that I can certify x, too.

**Comment by jeehoonkang** [comment]
- Test case 14: If a variable is marked volatile in the JMM test case, assume all loads/stores to the variable are acquires/releases.
- Test case 17/18: I cannot understand "However, when I tried to certify x as 42 in thread 1, it is impossible to recertify it because r3 is not 0, and recertification with x = 42 fails.".  Would you please elaborate more?

**Comment by integerblue** [comment]
I think recertification only succeeds when a thread is possible to write the promised value to a variable. 2nd line of the first thread is not true, so that 3rd line is not executed, and it seems impossible to recertify. Is recertification succeeds even if a thread cannot write the promised value to the variable, and if the variable already has the value in it? But it seems that thread 1 depends on thread 2 so that it cannot certify it, just like in test case 5.

**Comment by jeehoonkang** [comment]
> 2nd line of the first thread is not true, so that 3rd line is not executed, and it seems impossible to recertify.

The re-certification doesn't execute the same instruction to write X=42, but it still fulfills to write X=42 (via a different instruction).  In that case, we say the promise is re-certified.

The execution proceeds as follows for the test case 17:

- Thread 1 promises to write Y=42.  Certified via the X=42, r1=X, Y=r1 instructions.
- Thread 2 reads Y=42 and writes X=42.
- Thread 1 reads X=42 in r3=X.  Re-certified via r1=X, Y=r1 instructions.
- Thread 1 reads X=42 in r1=X.  Re-certified via Y=r1 instructions.
- Thread 1 fulfills the promise to write Y=42.

**Comment by integerblue** [comment]
What I meant is that promising X = 42 instead of promising Y = 42 seems impossible. Could you explain once again with promising X = 42 at the first place? If X is already 42, then X = 42 operation is not executed, so that recertufication seems to fail.

**Comment by jeehoonkang** [comment]
@integerblue Ah, I see.  It was my typo.  You're right: we cannot promise to write X=42 in the first thread.

**Comment by integerblue** [comment]
Thanks! Then one more question.
Is certification allowed only when execution is always executed? or is it allowed when there is a possibility for execution to be executed?
Like in case 5
```
Initially, x = y = z = 0

Thread 1:
r1 = x
if (r1 == 1)
  y = 1

Thread 2
r2 = y
if (r2 == 1)
  x = 1

Thread 3
z = 1

Thread 4
r3 = z
if (r3 == 1)
  x = 1

Behavior in question: r1 == r2 == 1, r3 == 0.

Decision: Forbidden. This is the same as test case 5, except using control
	dependences rather than data dependences.
```
Is it allowed to certify y = 1 in thread 1, because there is a possibility to execute it? or is it disallowed because it is not always executed?

**Comment by jeehoonkang** [comment]
- it is "allowed when there is a possibility for execution to be executed".
- But at the beginning, thread 1 cannot promise to write y=1 because the current memory (after arbitrary interference) doesn't have a message x=1 so that y=1 promise is not certified.

**Comment by integerblue** [comment]
In other words, when we want to certify something, it should be possible to execute using the memory state of that time, right?
Thanks!

**Comment by jeehoonkang** [comment]
@integerblue Yes, it is.  Additionally, you must certify for every possible future memory state: in certification, arbitrary messages may be arbitrarily inserted into the current memory.

**Comment by integerblue** [comment]
What do you mean by arbitrary messages and future memory state? Is it only about the memory state of the store execution or all other variables? Could you elaborate more on it with the examples above?

**Comment by jeehoonkang** [comment]
@integerblue I suggest you watch the video again: https://youtu.be/Av7QPv_foRU?t=1141  There, the arbitrary (e.g., "666") messages are inserted into the current memory for the certification.

**Comment by integerblue** [comment]
I understood what you mean by arbitrary messages. However, it seems that it is impossible to recertify in test case 17 with y = 42 in thread 1. Before executing r1 = x, there could be an arbitrary value from other thread in x, so that y = 42 might not be executed because of the interference of other thread. Then why y = 42 could be promised?
```
Causality test case 17
Initially,  x = y = 0

Thread 1:
r3 = x
if (r3 != 42)
  x = 42
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. A compiler could determine that at r1 = x in thread 1,
  is must be legal for to read x and see the value 42. Changing r1 = x 
  to r1 = 42 would allow y = r1 to be transformed to y = 42 and performed
  earlier, resulting in the behavior in question.
```

**Comment by integerblue** [comment]
@jeehoonkang Just in case if you forgot about this issue... I am waiting for the answer ;(

**Comment by zhanto97** [comment]
@integerblue It can be promised because Thread 1 can be optimized to
```
r3 = x
if (r3 != 42)
  x = 42
r1 = 42
y = r1
```
which, in turn, can be executed in below order
```
r1 = 42
y = r1
r3 = x
if (r3 != 42)
  x = 42
```

I hope that helps :)

**Comment by integerblue** [comment]
@zhanto97 I get that it can be optimized in that way, but I am curious that how it can be understood in promising semantics, without thinking about the compiler optimization.

**Comment by travis1829** [comment]
@integerblue 
Honestly, I think you're a better expert than me about promising semantics, but I'd still like to tell what I think about how we can understand about compiler optimizations in promising semantics.

What I think is that, considerations about compiler optimizations and reorderings are already implicitly done when we make and certify promises.

For example, as @zhanto97 said, the compiler/runtime processor knows that y will become 42 later, because according to the "intrathread" analysis done by the compiler/processor (that is, starting from initial messages such as x=y=0 and looking through only the instructions of thread 1), we get r1=42 at the end anyway. Hence, we can "move" the r1=42, y=r1 to an upper stage.

For me, such intrathread analysis is very similar to our process of "promising 42 and certifying". Our certification was done based on the thread's isolation and our initial messages, and this is similar to such "intrathread" analysis. However, instead of "actually doing the instructions" in an earlier stage, we just started with a promise y=42, and continued our analysis/execution from there. Whether such optimization will actually happen (in runtime) was verified using recertification.

Moreover, compilers/processors can do even more optimizations based on even more pre-runtime analysis or runtime analysis, and considerations about them are done when we "use previous promises to make more promises".

**Comment by integerblue** [comment]
@travis1829 Thank you for commenting on considerations of compiler optimizations in promising semantics. I thought they were totally different from each other so that it is fresh for me. But hoping @jeehoonkang to explain more on considering arbitrary values in promising semantics.

**Comment by jeehoonkang** [comment]
- @integerblue In test case 17, even if there're arbitrary interference, you already placed a message for Y=42 and thus it can be certified.

- @zhanto97 @travis1829 Even though the behavior is understandable with optimizations, this course requires you to reason about the examples with the promising semantics as @integerblue suggested.

**Comment by travis1829** [comment]
Yes, I understand. Actually, I also just wanted to say we can just use promising semantics instead.

**Comment by integerblue** [comment]
@jeehoonkang Could you elaborate more on arbitrary interferences?
I have not seen any case so far when arbitrary interference has an actual impact on certification or recertification so that I cannot get the importance of considering it.

**Comment by totolacky** [comment]
@integerblue How about considering the following example?
```
initial state: X=0

Thread 1:
    X.fetch_add(1)
```
Without arbitrary interferences, we would be able to promise X=1 and certify it. However, due to the arbitrary interferences, we won't be able to certify such a promise (which is in fact the desired behavior).

**Comment by integerblue** [comment]
> I understood what you mean by arbitrary messages. However, it seems that it is impossible to recertify in test case 17 with y = 42 in thread 1. Before executing r1 = x, there could be an arbitrary value from other thread in x, so that y = 42 might not be executed because of the interference of other thread. Then why y = 42 could be promised?
> 
> ```
> Causality test case 17
> Initially,  x = y = 0
> 
> Thread 1:
> r3 = x
> if (r3 != 42)
>   x = 42
> r1 = x
> y = r1
> 
> Thread 2:
> r2 = y
> x = r2
> 
> Behavior in question: r1 == r2 == r3 == 42
> 
> Decision: Allowed. A compiler could determine that at r1 = x in thread 1,
>   is must be legal for to read x and see the value 42. Changing r1 = x 
>   to r1 = 42 would allow y = r1 to be transformed to y = 42 and performed
>   earlier, resulting in the behavior in question.
> ```

Then what is the difference between this example? @jeehoonkang told me that y = 42 is already placed so it's okay, and in your example, X = 0 is already placed in the initial state, so it seems okay to certify X=1 as a promise.

**Comment by totolacky** [comment]
(To make a long story short: it is because fetch_add() is an atomic operation.)

I understood that we introduce arbitrary interferences only when we certify a promise. Intuitively, certifying a promise is to prove that 'under any interference by other threads, the thread can write that value'.

Let's see test case 17. The memory will look something like this with arbitrary interference.
```
X | [0][666]
Y | [0][666]{42}[666]
[]: message
{}: promise
```
Without loss of generality, we may assume that all messages are adjacent. As thread 1 may read either 0 or 666 (recall that enabling this was the whole purpose of introducing multi-valued memory), thread 1 **can** read X=0 and end up writing Y=42. This certifies the promise.

Now, let's see my example. The memory will look like this with arbitrary interference.
```
X | [0][666]{1}[666]
```
Note that fetch_add() is atomic, and it must be placed adjacent to the message that it read. For thread 1 to write X=1, it must write it adjacent to X=0. This is not guaranteed to be possible, as the interfering message 666 might already be adjacent to the initial X=0.

**Comment by integerblue** [comment]
That makes sense to me!
Then only the atomic operations are the reason why we care about arbitrary interferences? 
I am curious why @jeehoonkang didn't mention about this if this is the only cause we care about it.

**Comment by jeehoonkang** [comment]
- @totolacky Thank you for the detailed answer.
- @integerblue The reason was I didn't expect students to dig it such further.  Thank you all for leading a wonderful discussion.
