### ISSUE TITLE
[Question] java causality test

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#141]
It is very hard to understand promising semantics :(
I just want you to ask several questions about how to reason java causality test.

1) Certification 
Is it right that promise is certified when it **can** be happened for any circumstance?
For example, in test case #6,
    ```
     A=B=0
     r1 = A          || r2 = B
     if r1 >= 0 {B=1}|| if (r2 == 1) {A=1}
                     || if (r2 == 0) {A=1}
    ```
    Since A could be 1 due to second if-branch of thread-2, writing 1 to A is certified. Is it right? 

    If it is right, the reason why following case is forbidden is due to impossible recertification?
    ```
    X=Y=0
    r1 = X  || r2 = Y
    Y = r1  || if (r2 == 1) {X=r2}
            || else {X=1}
    ```
    I think using thread-2's else branch, I can promise that writing 1 to A. But Since it cannot be re-certified, it is forbidden. 
Am I right?

2) For forbidden case (test case #5)
In the earlier issue, professor said that to prove a case is forbidden, programmer should consider all possible cases. 
For causality test #5,
    ```
    x=y=z=0
    Thread 1:
    r1=x
    y=r1
    
    Thread 2:
    r2=y
    x=r2

    Thread 3:
    z=1
    
    Thread 4:
    r3=z
    x=r3
   ```
   I think r1==r2==1, r3==0 is forbidden since for r1, r2 to be 1, r3 should be 1. But how can I reason it using promising semantics? Use induction to prove the case is forbidden? 

   In most of the test, site prove some tests are forbidden using SC's the point of view. (case #13, #14, #15) Is it enough to prove forbidden cases? If not, how do I reason it? It seems that writing down all possible cases is too tricky.

3) Reasoning (test case #11)
And for causality test #11, I conclude the test is allowed for following reasons.

    1.  x = 1 is promised by thread 2
    2.  y = 1 is promised by thread 1. It is certified using promise that x = 1 (first promise)
    3.  z = 1 is promised by thread 2. It is certified using promise that y = 1 (second promise)
    4. With 1,2,3 promises, I can conclude r1=r2=r3=r4=1 <br/>
  
    What I wonder is for step 1, 2, 3, the promise is certified using previous promise. Am I right? 
  
4) test case #17 
Finally, I cannot understand why #17 is allowed. I think just like below.
    
    1. x=42 is promised by Thread 1
    2. Thread 1 read message x=42 in the first instruction. <-- here is the problem

    If Thread 1 read message x = 42 in the first instruction, can we say that promise x = 42 is re-certified by thread-1 even if it never write x=42 to memory? 

I will be really appreciated if you answer above questions.

**Comment by integerblue** [comment]
1. You're right.

2. case 5 is forbidden because we cannot certify anything because the values cannot come out of thin air.
I agree with you that proving a case to be possible is doable but disproving is not. 

3. You're right.

4. #130 #131 #135 #136 #137 would help you. Especially #136

**Comment by wltn0029** [comment]
Thank you for guiding me to understand promise :)

After reading recommend issues, I think I get some idea on promising semantic. (Actually, I **hope**)
But I want to ask some more questions.

1. out-of-thin-air
What is definition of **out-of-thin-air** ? I tried hard to find clear definition on the internet but I couldn't :( 
In my opinion, out-of-thin-air is the result from uncertified result. For example, causality test case 13,
    ***
    Initially, x = y = 0

    Thread 1:
    r1 = x
    if (r1 == 1)
      y = 1

    Thread 2:
    r2 = y
    if (r2 == 1)
      x = 1
    ***
    I think r1=r2=1 is disallowed because of out-of-thin-air. Since no case can promised either x=1 or y=1, r1 and r2 cannot be 1. 

    And also for test case 5, 
    ***
    Initially, x = y = z = 0
    
    Thread 1:
    r1 = x
    y = r1

    Thread 2
    r2 = y 
    x = r2

    Thread 3
    z = 1

    Thread 4
    r3 = z
    x = r3

    Behavior in question: r1 == r2 == 1, r3 == 0.
    ***
    For suggested behavior to be allowed, r3 should be zero, which implies z is zero. Therefore it is disproven using out-of-thin-air. Is it right? 

2. for volatile case
Professor said that promising semantic uses acquire/release semantic whenever it considers volatile variable. I think it implies **view**. For example, test case 14
    ***
    Initially, a = b = y = 0, y is volatile

    Thread 1:
    r1 = a
    if (r1 == 0)
      y = 1
    else
      b = 1

    Thread 2:
    do {
      r2 = y
      r3 = b
      } while (r2 + r3 == 0);
    a = 1;

    Behavior in question: r1 == r3 = 1; r2 = 0
    ***
    I disapprove it for following reasons.
    1) To be r1=1, promise a=1 is needed
    2) promise a=1 includes view in which either y or b is one 
    3) To be r3=1, promise b=1 is needed <-- here is problem
    Since promise r1=1 includes view in which either y or b is one, to fulfill suggested behavior, we should choose the view of b=1. But it leads impossible re-certification because at the time we try to write one to b (Thread 1 - else branch), it is already written by accepting view. Therefore, it is disallowed. Is it correct reasoning?

**Comment by jeehoonkang** [comment]
- Regarding "out-of-thin-air": unfortunately, there are no universally agreed-upon definition of this phenomenon.  You can think of the promising semantics as an attempt to "define" what's allowed and what's out-of-thin-air (and thus forbidden).

- For a concrete example, you need to reason about it using the promising semantics.  The notion of "out-of-thin-air" is at best informal and it cannot be used to formally reason about a certain behavior.  (Rather, the notion is quite normative, e.g., we often say the promising semantics **should** forbid a certain behavior becaues it's looking like out-of-thin-air.)

- For the reasoning for test case 14: I think your proof attempt is difficult to read because it doesn't describe the execution order.  For example, why "promise a=1 is needed"?  It's because you're implicitly considering the first instruction to execute.

  I suggest you classify all the executions by their first instruction.  Then it will lead a readable proof.

**Comment by totolacky** [comment]
For the volatile case (test case 5), would this be a valid proof?

(i) Suppose we run T2(thread 2) first.

In order to have r2=0 and r3=1, T1 must promise b=1.
For that promise to be valid, T2 must promise a=1.
However, the promise a=1 cannot be certified because if y=b=0 forever, then a=1 does not get executed.
Therefore, [r1=r3=1, r2=0] cannot be satisfied in this case.

(ii) Suppose we run T1 first.

In order to have r1=1, T2 must promise a=1.
However, due to the same reason as above, T2 cannot certify the promise.
Therefore, [r1=r3=1, r2=0] cannot be satisfied in this case, either.

+ Is the above proof redundant? In other words, is it enough to consider only one execution order of the threads?

**Comment by jeehoonkang** [comment]
@totolacky You mean test case 15, right?

I think your attempt still doesn't take into account the order of execution.  "T1 must promise b=1" when?


Here's my proof sketch:

- Without loss of generality, we may assume T3 first wrote x=1 at some timestamp.
- Let's think of the next message we promise to write.
    + If it were y=1, then then we will never be able to write b=1 and thus get the behavior in question.
    + It cannot be b=1, because T1 cannot fulfill it alone.
    + It cannot be a=1, because T2 cannot fulfill it alone.
    + It cannot be other messages, obviously.

**Comment by totolacky** [comment]
Sorry, I meant test case 15 😁 

Thanks for the outline! I just have a few more questions regarding your proof.

1. When considering the test case 15, I understood that we are assuming that any other arbitrary thread (other than T1 ~ T3) can concurrently access the memories a,b,x,y (instead of assuming that only T1~T3 are accessing the memory). I also thought this is the reason we are introducing the '666' values. Am I correct?

2. I think that in your proof sketch (for test case 15), the following theorem(?) is assumed to hold.
```
r0==r1==r3==1, r2==0 is allowed if and only if we can promise x=1, a=1, b=1, and y=0
```
(Perhaps we may discard the 'y=0' promise as it is the initial value, and we need no extra promise for it)
Is this theorem actually implied in your proof? If so, why does this hold?

3. Would the following proof for test case 6 be correct?
```
Initially A = B = 0

Thread 1
r1 = A
if (r1 == 1)
   B = 1

Thread 2
r2=B
if (r2 == 1)
    A = 1
if (r2 == 0)
    A = 1

Behavior in question: r1 == r2 == 1 allowed?
```
* We can promise to write A=1, and certify/recertify it.
* Given that promise, we can promise to write B=1, and certify/recertify it.
* As we have both promises A=1 and B=1, r1 can read 1 and r2 can read 1. Thus, the behavior is allowed.

Thaks a lot for your help!

**Comment by wltn0029** [comment]
> Regarding "out-of-thin-air": unfortunately, there are no universally agreed-upon definition of this phenomenon. You can think of the promising semantics as an attempt to "define" what's allowed and what's out-of-thin-air (and thus forbidden).
That's why I failed to find definition.. :( 
Then, for test case#5 how can I disapprove it using promising semantics? I think following steps. 
1) z = 1 is certified by thread 3. 
2) 1) certifies x=1 by thread 1.
3) 2) certifies y=1 by thread 2. 
4) Assume that thread 1 is executed first. And it choose to read promise x = 1. And as a result, y = 1 is re-certified.
5) thread 2 is  executed next. It choose to read promise y = 1. And as a result, x = 1 is re-certified.
6) thread 4 is executed. It do not choose to read promise z=1 for r3 to be 0.
7) thread 3 is executed and z = 1 is re-certified.
I know it is definitely wrong reasoning, but I cannot find my mistake. Which step is wrong?

**Comment by jeehoonkang** [comment]
### Regarding @totolacky's questions

1. Even though there are only three threads, from a certain thread's perspective when certifying, we don't "exploit" the fact that there are only three threads.  In that sense, you're right: we're not assuming there are three threads in certification.

1. I'm not particularly assuming the theorem you've described.  Probably you're asking why the following sentence holds:

    > If it were y=1, then then we will never be able to write b=1 and thus get the behavior in question.

    The reason is that if `y=1` is promised, than it must be fulfilled and `b=1` can never be written.  Thus T2 cannot read `b=1` and `r3` must be zero.



### Regarding @wltn0029's questions

1. I don't understand what does it mean by "z = 1 is certified by thread 3." or "step 1 certifies x=1 by thread 1."  Do you mean z=1 and x=1 are promised?  If so, how?

1. I don't understand what does it mean by "In this case, it certifies a=1 with the view that y and b is zero. And it implies that r3 can never be 1.".  This comment may help you understanding test cases 14 and 15: https://github.com/kaist-cp/cs492-concur/issues/141#issuecomment-712950417

**Comment by wltn0029** [comment]
@jeehoonkang 
1. I just thought that previous promise can be used to certify another thread. But I found that it can't be. Then is it ok to consider some reordering when prove something is right? 
`Initially, x = y = z = 0

Thread 1:
r1 = z
r2 = x
y = r2

Thread 2:
r3 = y
z = r3
x = 1

Behavior in question: r1 = r2 = r3 = 1.`
Above test case #7, I cannot find how to prove it except for explicitly using a knowledge that thread1's first instruction could be executed later than other instruction.
질문을 한국어로 드리면, 제가 처음에는 이전 promise 를 이용해서 다음 promise 를 유도할 수 있을 것이라 생각했는데, 이후에 달린 답변을 참고했을 때 그것이 잘못된 생각이라는 것을 알았습니다. 그런데 그럴 경우 test case #7 을 증명할 때 직접적으로 r1이 나중에 실행되는 경우를 이용해야 할 것 같아서 이것이 맞는 증명 방법인지 여쭙고 싶습니다.

**Comment by jeehoonkang** [comment]
Here's an execution that leads to the behavior in question:

- T2 promises to write x=1.  It's certified: regardless of the value read at r3=y, it can fulfill the message.
- T1 promises to write y=1.  It's certified: regardless of the value read at r1=z, it can read x=1 at r2=x and fulfill the message.
- T2 reads y=1.  It's re-certified: it can write z=1 and fulfill the message x=1.
- T2 write z=1.  It's re-certified: it can fulfill the message x=1.
- T2 fulfills x=1.
- T1 reads z=1.  It's re-certified: it can read x=1 and fulfill y=1.
- T1 reads x=1.  It's re-certified: it can fulfill y=1.
- T1 fulfills y=1.
