### ISSUE TITLE
[Question] Ownership movement in try_unwrap

### ISSUE THREAD

**Issue by c0m0r1** [kaist-cp/cs492-concur#142]
I simply tried to return `*this.deref()` or `(*this.ptr.as_ptr()).data` to implement `try_unwrap`. However, compiler displays the following error for ownership transfer reasons:
```
error[E0507]: cannot move out of `*data` which is behind a shared reference
   --> src/arc.rs:208:20
    |
208 |                 Ok(*data)
    |                    ^^^^^ move occurs because `*data` has type `T`, which does not implement the `Copy` trait
```
Should we need to use special function to implement `try_unwrap` except `mem::forget`? Or there's any other approach to solve this problem?

**Comment by tomtomjhj** [comment]
`(*this.ptr.as_ptr()).data` is almost correct but this won't work because Rust doesn't associate ownership with raw pointers. `Box::from_raw` converts the raw pointer to `Box` which asserts the ownership of the allocated data.

**Comment by Ngiong** [comment]
Hello @tomtomjhj 
I also have a question regarding "ownership movement" when using `mem::forget`
From the API documentation of `mem::forget`, it is written: **Takes ownership** and "forgets" about the value without running its destructor.

I understand that it's required to use `mem::forget` so that the value from dereferencing the raw pointer (i.e. using `Box::from_raw`) will not get destructed when the Box lifetime has ended.

But I still can't understand how we can still own the value we put to `mem::forget`, as `mem::forget` "takes ownership" (as written in the documentation). AFAIU, we must somehow own the value as the return value of `try_unwrap`, but this ownership is "_lost_" after the `mem::forget` call. Am I missing something here?

Thank you.
--
p.s. I think this issue highly relates to my question, so I posted it here to reduce too many new issues.

**Comment by tomtomjhj** [comment]
Here "taking ownership" is just describing the type signature. We **say** a function takes ownership of a value of type `T` if it takes `T` as an argument. In 100% safe rust this means that the function **indeed** takes the ownership. However in unsafe Rust, this correspondence between the type system and the actual behavior of the program can be (temporarily) broken. For example, `try_unwrap` returns the ownership of `T` while at the same time it's `mem::forget`'ed. So when we write Rust with safe API but unsafe internals, we should prove that this correspondence is preserved if the user uses the API in 100% safe context.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen this issue if you have further questions!
