### ISSUE TITLE
[Question] HW3 TC Explanation (make_mut & drop)

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs492-concur#150]
Hello,

I'm currently doing HW3 and I'm having difficulty understanding the `make_mut` API (and its description).
I've tried to read the Rust's Arc documentation too, but I couldn't get an answer there as their example is exactly the same as our HW's example.
```rust
use cs492_concur_homework::Arc;

let mut data = Arc::new(5);

*Arc::make_mut(&mut data) += 1;         // Won't clone anything      ...(1)
let mut other_data = Arc::clone(&data); // Won't clone inner data    ...(2)
*Arc::make_mut(&mut data) += 1;         // Clones inner data         ...(3)
*Arc::make_mut(&mut data) += 1;         // Won't clone anything      ...(4)
*Arc::make_mut(&mut other_data) *= 2;   // Won't clone anything      ...(5)

// Now `data` and `other_data` point to different allocations.
assert_eq!(*data, 8);
assert_eq!(*other_data, 12);
```
In line (1), I understand why make_mut should not clone anything (because it's unique Arc)
However, I can't understand why line number (3) and (4) have different behavior, although the state should be same (in (3) & (4), the data is not a unique Arc). Also I don't understand line number (5) why we should not clone anything, since `other_data` Arc should not be unique either (?) [I thought we should clone if the Arc is not unique] 

In addition, I also want to ask clarification for this TC.
```rust
#[test]
fn drop_arc() {
    let mut canary = AtomicUsize::new(0);
    let x = Arc::new(Canary(&mut canary as *mut AtomicUsize));
    let y = x.clone();
    drop(x);
    drop(y);
    assert!(canary.load(Relaxed) == 1);
}
```
After reading this TC for so many times, I'm still not able to reason why canary variable should be == 1
After only putting it an Arc, clone the Arc, and drop both 2 Arcs. Can I also get an explanation of this TC?

Thank you.

**Comment by YujinGaya** [comment]
For `make_mut`,
(1) data -> Arc { count: 1, data: 5 }
(2) data, other_data -> Arc { count: 2, data: 6 }
(3) data -> Arc { count: 1, data: 7 }, other_data -> Arc { count: 1, data: 6 } // Make new Arc since data has count = 2
(4) data -> Arc { count: 1, data: 8 }, other_data -> Arc { count: 1, data: 6 }
(5) data -> Arc { count: 1, data: 8 }, other_data -> Arc { count: 1, data: 12 }

For the test case `drop_arc`, it's 1 because canary only dropped once.

It will be easier to help you If you tell me your expected value for `canary.load(Relaxed)` at the end.

**Comment by tomtomjhj** [comment]
`Arc` is the pointer for arbitrary sharing of immutable (or interior-mutable) data in the heap. `Arc::clone` is for creating another pointer to the shared data. Dropping an `Arc` means that you no longer want to the shared data. Dropping an `Arc` doesn't necessarily imply the destruction/deallocation of the data because the data might be shared. So the data can be dropped only if there is no `Arc` pointing to that data.

Normally you can't get `&mut` of the underlying data from an `Arc`, because the data might be shared and the owners of the other instance of `Arc` to the shared data don't expect the data to be mutated. `get_mut` and `make_mut` can get `&mut` of the the data because they ensure that the data is not actually shared. `get_mut` returns `&mut` only if the count is 1 while `make_mut` always returns `&mut` by cloning the data if the data was shared. So `make_mut` is basically for copy-on-write (or clone-on-write in the context of Rust) behavior.

**Comment by Ngiong** [comment]
@YujinGaya 
I think now I understand regarding the `make_mut`

For `drop_arc`,
Oh you're right. I forgot to add my expected value.
I thought it should be 0, because putting the value into the Arc, clone the Arc, and dropping the Arc should not modify the underlying value. Therefore, I still don't quite get why it's should be 1.

Can you elaborate more details on this?
Thank you ^^

**Comment by tomtomjhj** [comment]
`Canary` is a wrapper of a pointer to a counter on stack that gets incremented when the wrapping `Canary` gets dropped. It's an apparatus for testing if the `Drop` implementation for `Arc` drops the underlying data only once.

**Comment by Ngiong** [comment]
I see. That's the point that I missed.
Thank you for your clarification :grin:
