### ISSUE TITLE
[Question] Promises with multiple stores, and intuition behind certification.

### ISSUE THREAD

**Issue by totolacky** [kaist-cp/cs492-concur#161]
[1. Promises with multiple stores to the same location]
Consider the following example.
```
initial state: X=Y=0

Thread 1: r1 = Y; X = 1; X = 2
Thread 2: r2 = X; Y = r2
```
Say that we want to check if [r1=r2=1] or [r1=r2=2] is possible. Here, I thought that Thread 1 can promise to write X=1 and X=2 and it can certify those promises, but fails to re-certify X=2 (because otherwise, X=2 should be written before X=1). Therefore, [r1=r2=1] is possible with the promise X=1, but [r1=r2=2] is impossible, as it requires the promise X=2. Am I precisely correct? (Is there something more that I have to say in order to claim that [r1=r2=2] is impossible?)

[2. The intuition behind certification]
From the above example, I thought that the intuition behind certification and re-certification is as follows.
```
Certification: Check if the thread "can" write that value, no matter what other threads are doing.
Re-certification: Check...
(1) if the thread "always" writes the promised value when interleaving with another specific thread (so that hoisting is possible)
(2) if such hoisting violates coherence.
```
Would this be a correct understanding? For example, consider the following.
```
Initial condition: X=Y=0
r1=X || r2=Y
Y=r1 || if r2==1 { X=2 } else { X=1 }
```
I think that the promise X=1 can be certified, but cannot be re-certified. Am I correct?

Thanks in advance 😀

**Comment by integerblue** [comment]
1. 
X=Y=0

T1       |    T2
r1 = Y | r2 = X
X = 1  | Y = r2
X = 2  |

In this example, let's certify X = 2 at the beginning. X = Y = 0 so that through the following instructions of T1, we could easily certify X = 2 could be promised. Then, r2 = X can be executed, and still, X = 2 can be recertified because X = 2 does not require any other memory state. Y = R2, r1 = Y, X = 1 as follows. Finally, X = 2 can be executed and the promise is fulfilled. 

2. 
I think you're right. But I am still confused about whether all the possibilities of interleavings should be considered that recertification could be possible or not.
For example,

```
Initial condition: X=Y=0
r1=X || r2=Y
Y=r1 || if r2==1 { X=2 } else { X=1 }
```

After promise and certification of X = 1, r1 = X, r2 = Y could be executed, which enables X to be 1 in thread 2. Y = r1 could be finally executed so that recertification and fulfillment of the promise are done.

**Comment by totolacky** [comment]
Thanks for answering!

1. I guess I gave a bad example! I intended to create an example where X=2 should be hoisted across X=1 so that the promise fails, but this example allows the reordering of r1=Y. How about considering the following example?
```
X=Y=0
T1     || T2
X = 1  || r1 = X
X = 2  || r2 = X
is [r1=2, r2=1] possible?
```
In this case, what would the promise look like? Would it be correct to think that T1 gives two promises X=1 and X=2 so that the promise X=2 appears later than X=1 in the timestamp?

2. I think recertification at every possible interleaving should be done, as 'promising' a value means that store hoisting is allowed to happen. In the above example, recertification fails if we execute T1 first, and then execute T2. This means that X=1 cannot be written in some interleavings, and therefore store hoisting of X=1 cannot happen.

**Comment by integerblue** [comment]
1.
I think promising only X=2 in T1 could be possible, so that r1 = X, X = 1, r2 = X, X = 2 could be executed consequently.
Promising both values in order X = 2 and X = 1 would occur in failure of recertification of X = 2 because after the promise X = 1 is fulfilled, X = 2 cannot be recertified because the timestamp is less or equal than current timestmap. 

2.
I agree that in that case recertification could be failed, so I am waiting for the answer of the instructor @jeehoonkang.

**Comment by totolacky** [comment]
1.
I meant that we might be able to promise both values in order X=1 and X=2. This way, both promises can be fulfilled.

**Comment by integerblue** [comment]
1. You're right, but then the promise of X = 1 is overwritten by X = 2 so it seems meaningless to me.

**Comment by gunwooterry** [comment]
Example from the question 2:
```
Initial condition: X=Y=0
r1=X || r2=Y
Y=r1 || if r2==1 { X=2 } else { X=1 }
```
I believe in this case, neither X = 1 nor X = 2 can be certified. They are not semantically independent.

**Comment by integerblue** [comment]
Then how could you acknowledge two operations are semantically independent or not? I thought certification and recertification is the way to figure out whether they are. Therefore, somehow certification or recertification should fail in the steps, but as I've mentioned, the following specific steps result in successful certification and recertification, which is what I am confused about. Therefore all thread interleavings seem to be concerned at all stages, but that is a conflicting thought from my original understanding so that I am waiting for the answer of @jeehoonkang... I hope there would've been a concrete procedure for the promise, certification, and recertification.

**Comment by jeehoonkang** [comment]
## For @totolacky's original post

- You can get the behavior by (1) T1 promising to write X=1; (2) T1 promising to write X=2; (3) T2 reads X=2; (4) T2 writes Y=2; (5) T1 reads Y=2; and (6) T1 fulfills X=1 and X=2 in series.  The key here is promising to write two messages, X=1 and X=2.  If you only promise to write X=2, then you cannot fulfill it because the other threads may interfere by fulling occupying the timestamps before the X=2 message, disallowing T1 to write X=1 before X=2 in the certification.

- The intuition for certification and re-certification is actually the same: "Check if the thread "can" write that value, no matter what other threads are doing."  It doesn't change for re-certification.  I don't quite understand your example.  Would you please elaborate?  You can write in Korean.  It's beneficial to present (1) code example, (2) behavior in question, and (3) an execution you're thinking of.


## For @totolacky's first comment

- Even if you can promise some writes, X=1 must be placed before X=2 in the memory.  It's mandated by the coherence rules.

**Comment by jeehoonkang** [comment]
@integerblue I don't understand your last comment.  Would you please write in Korean?

**Comment by integerblue** [comment]
@jeehoonkang 

- Then how can a thread occupy the timestamps before the X=2 message? fetch_sub can't do that because its timestamp could be ended before the X=2 message. 
- 다른 thread가 어떤 일을 하더라도 value를 쓸 수 있어야 한다는 말이 명확하지 않은 것 같습니다. 만약 어떤 timestamp에 666이라는 arbitrary value가 들어와있고, promising thread가 아닌 다른 thread가 해당 arbitrary value를 읽는다면 promising thread의 recertification이 fail하는 상황까지도 고려를 해야 하는 건가요? 아래와 같은 상황에서 T2에서 A=1을 promise하고 다른 thread에 의해 666이라는 arbitrary value가 끼어있는 상황에서 T1이 r1=A에서 666을 load한다면 A=1은 recertification에 실패할 수밖에 없습니다. 그렇다면 내가 선택한 message view로 이동하는 상황에서만 certification, recertification이 성공하면 되는지 궁금합니다.
```
Initially A = B = 0

Thread 1
r1 = A
if (r1 == 0 || r1 == 1)
   B = 1
else
   B = 2

Thread 2
r2=B
if (r2 == 1)
    A = 1
if (r2 == 0)
    A = 1

Behavior in question: r1 == r2 == 1 allowed?
```

**Comment by integerblue** [comment]
```
Initial condition: X=Y=0
r1=X || r2=Y
Y=r1 || if r2==1 { X=2 } else { X=1 }
```
이 예시에서 최초 T2에서 X=1 promise 및 certification은 성공합니다. X, Y = 0인 초기 memory state에서 실행가능하기 때문입니다.
T1에서 r1=X가 실행되고 r1에 1을 넣은 후 r2=Y에서 0을 넣는다면 X=1 promise recertification이 성공하고, fulfill되게 됩니다.
하지만 r1=X 이후 Y=r1이 실행이 먼저된다면 r2=Y는 1을 load하기 때문에 X=1을 실행할 수 없습니다.
이와 같이 memory view를 어떻게 이동시키냐에 따라서 promise가 certified 될 수 있는지 없는지가 갈리는 것처럼 보이는데, 위의 arbitrary value에서와 같이 내가 원하는 memory state으로 옮겨갈 수 있다고 한다면 X=1 promise가 성공하여야 하고, 그렇지 않다면 실패하여야 하지만 그렇다면 arbitrary value에서 어떻게 내가 원하는 memory state으로 옮겨갈 수 있는지가 궁금합니다.

**Comment by integerblue** [comment]
@jeehoonkang 또, X=1과 X=2 promise를 두 번 연달아 해야 한다는 것에 대해서 질문드리자면, 만약 store operation이 두 번 나오면 두번째 operation을 promise하기 위해서는 꼭 이런 식으로 앞의 operation도 promise 해줘야 하는 것인가요? 
```
T1
if some_condition {
  X = 1
}
X = 2
```
만약 그렇다면 이와 같이 if 문 안에 store operation이 있어 실행되지 않을 수도 있는 경우엔 첫번째 operation은 promise 할 수 없는데 만약 some_condition이 충족되어 X=1이 실행되지 못하는 경우가 생길 수도 있지 않나요?

**Comment by totolacky** [comment]
@jeehoonkang Thanks for your answers.
1. Is it necessary to mention step (6) in the proof? I think this should be already checked when we promise x=2.
2. 해당 예시에서 T2가 X=1을 promise할 수 있는지 확인하는 과정에서, certification은 성공하고 recertification은 실패하는 것이 맞는지(제가 제대로 이해했는지)가 궁금합니다.
```
Initial condition: X=Y=0
r1=X || r2=Y
Y=r1 || if r2==1 { X=2 } else { X=1 }
```
3. Store hoisting과 promise 사이의 관계에 대해 계속 헷갈리고 있습니다. 질문의 의도를 더 잘 표현하기 위해 다른 예시를 들자면,
```
Initially X=Y=Z=0

T1:
  r1 = Y
  X = 1
  r3 = Z
  if (r3 == 0)
    X=2

T2:
  r2 = X
  Y = r2
```
이러한 예시에서, T1이 X=1을 promise하고, 이후에 X=2를 promise할 수 있다는 것까지는 이해가 됩니다. Store hoisting의 관점해서 이야기해보면 이것은 X=2가 X=1 이후의 어느 지점(ex> r3=Z 직전)으로 hoisting될 수 있다는 의미라고 이해했는데요, 실제로 프로그램이 돌아갈 때는 Z 위치에 어떤 값이 들어올지 모르므로 X=2를 hoisting해서는 안 된다는 생각이 들었습니다.

정리하자면, X=2를 promise한다는 것이 X=2를 (X=1 instruction 이후의) 임의의 지점으로 hoisting할 수 있다는 의미인지 궁금합니다.

**Comment by integerblue** [comment]
```
# Test case 2
Initially, x = y = 0

Thread 1:
r1 = x
r2 = x
if r1 == r2
  y = 1

Thread 2:
r3 = y
x = r3

Behavior in question: r1 == r2 == r3 == 1

Decision: Allowed, since redundant read elimination could result in simplification
	of r1 == r2 to true, allowing y = 1 to be moved early.

Notes: In SC executions, both reads of x always return the same value (i.e., zero),
	so that r1 == r2 is always true in SC executions.
```
이 test case에서 T1에서 먼저 Y=1 promise 및 certification을 진행합니다. 이때 T1에서 r1=x로 r1에 0을 가지고 오고 T2에서 r3=y; x=r3, T1에서 r2=x를 실행하면 y=1의 recertification이 실패하게 됩니다. 따라서 이 경우까지 포함하여 생각하게 된다면 Y=1의 promise는 불가능한 것이 맞습니다. 만약 이 promise가 가능하게끔 하고 싶다면 모든 thread interleaving을 고려하지 않고 내가 원하는 순서의 thread interleaving 위에서 certification / recertification 만이 성공하면 되는 것인지 궁금합니다.

**Comment by totolacky** [comment]
@integerblue The case you just suggested does not fail the recertification.
Let's say that
1. T1 executed 'r1=x' so that r1=0.
2. T2 executed 'r3=y', 'x=r3' to read r3=1 and write x=1.
3. T1 executes 'r2=x'
Note that in step 3, T1 **can** still read x=0 because its per-thread-view is still at the message X=0. Thus, you can choose to read X=0 and thus write y=1, satisfying the promise.

**Comment by integerblue** [comment]
@totolacky That was exactly my question! Are we allowed to choose to satisfy a promise, or not allowed because we should satisfy the promise in all possible ways, including thread interleavings and message choices? So did you mean that only thread interleavings should be considered and message views are not?

**Comment by totolacky** [comment]
Now I get your question! I was (implicitly) thinking that for a promise to be (re)certified, the following should hold.
```
For "every" thread interleaving, 
there must "exist" a choice of messages to read such that the thread eventually writes the promise'.
```
However, I agree that I have no good reason why this holds. It's a great question!

**Comment by integerblue** [comment]
Thank you for pointing out my question in a neat sentence. Unless @jeehoonkang answers our questions, I would probably stick to the proposition you drew out in the midterm exam, if any problem with promising semantics is written there.

**Comment by totolacky** [comment]
> @jeehoonkang 또, X=1과 X=2 promise를 두 번 연달아 해야 한다는 것에 대해서 질문드리자면, 만약 store operation이 두 번 나오면 두번째 operation을 promise하기 위해서는 꼭 이런 식으로 앞의 operation도 promise 해줘야 하는 것인가요?
> 
> ```
> T1
> if some_condition {
>   X = 1
> }
> X = 2
> ```
> 
> 만약 그렇다면 이와 같이 if 문 안에 store operation이 있어 실행되지 않을 수도 있는 경우엔 첫번째 operation은 promise 할 수 없는데 만약 some_condition이 충족되어 X=1이 실행되지 못하는 경우가 생길 수도 있지 않나요?

Back to a previous discussion, we can't actually promise X=1 nor X=2 in this case. If we hoist any of the two store instructions, the semantics will change in the single-threaded case.

**Comment by integerblue** [comment]
@totolacky Yeah, I agree. I think I came up with a bad example. The necessity of promising both executions seemed to be strange, but I think I should accept it.

**Comment by integerblue** [comment]
@jeehoonkang @totolacky If we could choose which messages to use, then why recertification is required? If initial certification succeeds, then a thread could always stick to the initial memory state and recertification would always succeed, and only when it needs to fulfill its promise or be executed its lines. I think that if a promising thread is not executed, then other threads cannot affect the promising thread at all because of the initial memory state. And only when the promising thread needs to execute and wants to use the other thread's memory state, it needs to recertify. Am I correct?

**Comment by tomtomjhj** [comment]
>  thread could always stick to the initial memory state

Certification is done in the arbitrary extension (the 666 stuff from the lecture slides) of the current memory.

**Comment by integerblue** [comment]
@tomtomjhj 
What do you mean? A thread cannot stick to the initial memory state in certification/recertification?

**Comment by tomtomjhj** [comment]
@integerblue https://meet.google.com/ftr-epmw-pmv

**Comment by integerblue** [comment]
@tomtomjhj I think I got it. So, we already considered arbitrary interferences at the initial certification so that we don't need to recertify every time when the other threads execute their operations?

**Comment by jeehoonkang** [comment]
### Regarding @totolacky's questions

1. Even though there are only three threads, from a certain thread's perspective when certifying, we don't "exploit" the fact that there are only three threads.  In that sense, you're right: we're not assuming there are three threads in certification.

1. I'm not particularly assuming the theorem you've described.  Probably you're asking why the following sentence holds:

    > If it were y=1, then then we will never be able to write b=1 and thus get the behavior in question.

    The reason is that if `y=1` is promised, than it must be fulfilled and `b=1` can never be written.  Thus T2 cannot read `b=1` and `r3` must be zero.



### Regarding @wltn0029's questions

1. I don't understand what does it mean by "z = 1 is certified by thread 3." or "step 1 certifies x=1 by thread 1."  Do you mean z=1 and x=1 are promised?  If so, how?

1. I don't understand what does it mean by "In this case, it certifies a=1 with the view that y and b is zero. And it implies that r3 can never be 1.".  This comment may help you understanding test cases 14 and 15: https://github.com/kaist-cp/cs492-concur/issues/141#issuecomment-712950417




### Regarding @integerblue's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713331511

- > T1이 r1=A에서 666을 load한다면 A=1은 recertification에 실패할 수밖에 없습니다.

    It says, "if T1 reads 666 at r1=A, A=1's recertification must fail."

    First of all, (Re-)certification is a single thread's business.  T2's certification has nothing to do with T1.  So "666" may appear only at T2's certification and T1 cannot read 666 in actual execution.  Because certification is not a real execution that affects the memory.

    Second, even if there is a 666 message in the memory, T2 can read B=0 and writes A=1.


### Regarding @integerblue's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713334559

- > 하지만 r1=X 이후 Y=r1이 실행이 먼저된다면 r2=Y는 1을 load하기 때문에 X=1을 실행할 수 없습니다.

    It says, "if r1=X and then Y=r1 are executed, then r2=Y must load 1 and X=1 cannot be executed."

    Even if T1 writes `Y=1` at `Y=r1`, T2 can still read `Y=0` at `r2=Y` because its view is still on the initial message.


### Regarding @integerblue's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713340853

- That's a very good question. It says, for the given program, is it possible to promise `X=2` even if `X=1` is in a conditional branch.

    If, at the current program counter, you can "manage" to make `some_condition` true, then you can promise X=1 and X=2 in series.  If you can "manage" to make `some_condition` false, then you can promise X=2 only.  Either of this should happen because, in certification, `some_condition` will be evaluated to a certain value.


### Regarding @totolacky's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713344662

1. (6) is necessary because it concludes the execution of this program.

1. To see whether (re-)certification is successful, you need to provide behavior and execution.  What's the behavior in question?  What's the exeuction that results in the behavior?

1. At the beginning of T1, you can promise to write X=1 and X=2.  That means X=1 and X=2 can be hoisted to the beginning of T1.

    By doing so, we're effectigvely committing to read Z=0 at `r3=Z`.  So even though the other threads may write some values to `Z`, it will read `Z=0` and then fulfill `X=2.`  It T1's promise.

**Comment by totolacky** [comment]
Thanks for your answers.
For a quick last-minute thought about certification and re-certification... is this a correct understanding?
1. Certification is checking if a thread can write a certain value, even with arbitrary interference. The thread can **promise** to write the value when the behavior is certified.
2. Re-certification is checking if a given behavior (ex> r1=r2=0, r3=1) is possible to occur (even with arbitrary interference). At the end of re-certification, the 'promising' threads must be able to write their promises.

**Comment by jeehoonkang** [comment]
@totolacky No, we're certifying and re-certifying promises.  (Re-)certification is checking if a thread is able to fulfill its promises even with arbitrary interferences.

**Comment by totolacky** [comment]
@jeehoonkang Then would this rephrasing be correct?

1. Certification is checking if a thread can fulfill its promise on its own (even with arbitrary interferences).
2. Re-certification is checking if the thread can fulfill its promise, while also satisfying a given behavior (ex> r1=r2=0, r3=1) (even with arbitrary interferences).

**Comment by jeehoonkang** [comment]
### Regarding @integerblue's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713500911

- In T1's certification, T2 has nothing to do with it.  T1 alone is able to promise to write `y=1`. Please see [this comment](https://github.com/kaist-cp/cs492-concur/issues/168#issuecomment-713905856) for test case 2.


### Regarding @totolacky's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713513362

- In T1's (re-)certification, we don't consider interleaving with T2 or the other threads.  T1 is certified alone.  But at the beginning of the certification, we add arbitrary messages to the memory that models the interferences of arbitrary threads (not only from T2).



### Regarding @integerblue's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713732319

- Recertification is needed because a thread, say T1, that has promised to write W=1, may choose different behaviors.  For example, in certification T1 read Z=1, but in actual execution, it may read Z=2 that makes it impossible for T1 to fulfill W=1.  We want to forbid that by mandating, in re-certification, that T1 should always be able to fulfill W=1.


### Regarding @totolacky's question https://github.com/kaist-cp/cs492-concur/issues/161#issuecomment-713912840

- No.  "while also satisfying a given behavior (ex> r1=r2=0, r3=1) (even with arbitrary interferences)." is unnecessary.  (Re-)certification just decides which promises are possible in an execution.  Then an execution satisfies a certain behavior or not.

**Comment by totolacky** [comment]
@jeehoonkang Then, what is the difference between certification and recertification? Are we doing the exact same thing?

**Comment by jeehoonkang** [comment]
@totolacky Right, they are actually the same.  The only difference is that certification is for the steps that introduce promises, and (re-)certification is for the other steps.  Except that, they are the same.

**Comment by totolacky** [comment]
@jeehoonkang So...
1. We need to do certification when we introduce a promise.
2. When we are checking if a certain behavior is possible (using the previous promises), we also introduce arbitrary interference and check if the promised values can be written. This process is called re-certification.
Is this a correct understanding?

**Comment by jeehoonkang** [comment]
I think it's confusing to correlate behaviors and re-certification.  Re-certification is just checking a certain promise is still fulfillable.  Later we'll think of behaviors, but re-certification itself is (just like certification) not specific to a certain behavior.

**Comment by totolacky** [comment]
> 2\. To see whether (re-)certification is successful, you need to provide behavior and execution.  What's the behavior in question?  What's the exeuction that results in the behavior?

This was the part that I got confused. In the above reply, you said that I need to provide behavior and execution in order to see whether (re-)certification is successful.

**Comment by jeehoonkang** [comment]
@totolacky Ah, yes, indeed the quoted text is confusing.  Sorry.  What I meant is, in general, you need to provide execution and the goal behavior in order to ask a question on an example.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen this issue if you have further questions!
