### ISSUE TITLE
[Question] Difference between register and a memory in terms of concurrency

### ISSUE THREAD

**Issue by aujinsky** [kaist-cp/cs492-concur#165]
More specifically, why is it okay not to track the values of registers in the Promising semantics?
Is it just because memory is per-thread but registers are global? If so, does that means we should start considering it if having multiple processors?
Or it suffices to only track memory since every load and store always coincide with memory?

Thank you for the answers.

**Comment by totolacky** [comment]
In this course, we are considering shared-memory concurrency (as specified in the [slides](https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g950aa4a629_95_3)). Therefore, we are focusing on 'what happens on the **shared storage**'. 

Just like you intended to say, I think we're only tracking memories because registers are per-thread and thus **not shared among threads**, but memories are **shared**.

**Comment by jeehoonkang** [comment]
I agree with @totolacky.  Registers are local to a specific CPU or thread, so there are no challenges in modeling their behavior: jsut read and write to the local storage.  Memory, on the other hand, is shared among multiple CPUs/threads so its behavior is interesting as discussed in the slides.  We specifically distinguish memory and register to facilitate such a discussion.
