### ISSUE TITLE
[Question] Why do we clone the thread in MCS Parking lock?

### ISSUE THREAD

**Issue by YujinGaya** [kaist-cp/cs492-concur#176]
https://github.com/kaist-cp/cs492-concur/blob/0f48945abfa6259566b8b6a347b8118c8f582648/lock/src/mcsparkinglock.rs#L69-L76

I understood why we have to _store_ first from the [class](https://youtu.be/j0demG9TU6s?t=1329). It's because if we _unpark_ first and the thread got interleaved to the locking thread they would see false value and get parked again which results in deadlock.

But why should we _clone_ the thread? What if we just do it this way

```rust
let next = (*node).next.load(Ordering::Acquire);
if !next.is_null() {
    drop(Box::from_raw(node));
    /* we don't clone here */
    (*next).locked.store(false, Ordering::Release);
    (*next).thread.unpark(); // just unpark
    return;
}
```

To check whether it's right or wrong, I ran the [smoke test case](https://github.com/kaist-cp/cs492-concur/blob/0f48945abfa6259566b8b6a347b8118c8f582648/lock/src/lock.rs#L140-L158).

By reordering the instruction so that we unpark first, which is known to be wrong, I could easily reproduce the deadlock. It happened like once every four times. I could see the test case doesn't finish.

```
lock git:(master) ✗ cargo test mcsparkinglock
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running target/debug/deps/lock-a987959d24e1f0a2

running 1 test
test mcsparkinglock::tests::smoke ... test mcsparkinglock::tests::smoke has been running for over 60 seconds
```

But the alternative I proposed earlier compiled fine and passed the test.

My best guess was that maybe `unpark` function takes the ownership of the `Thread` so we need to make an ownership over a thread variable, [but it isn't](https://doc.rust-lang.org/std/thread/struct.Thread.html#method.unpark). It only requires immutable reference. Also we know for sure that the thread field of a `Node` does not get mutated anywhere.

So why do we need to clone the thread first?

**Comment by jeehoonkang** [comment]
Thank you for a deeph question.  The reason is that, in your program, the execution may proceed as follows:

- Thread B is calling lock().  prev.next = nodeB is written, but node.locked is not read yet (and it's not parked).
- Thread A is calling unlock().  nodeB.locked = false is written, but B is not yet unparked.
- Thread B's lock() reads node.locked = true, and return token.  Then Thread B calls unlock(), in which nodeB is deallocated.
- Thread A's unlock() calls nodeB.thread.park(), but nodeB is already deallocated.  So it's use-after-free.

I hope it answers your question.

**Comment by YujinGaya** [comment]
Oh, that makes perfect sense. I assumed the thread field won't be changed by looking at the code but I didn't noticed it can be deallocated/invalidated by drop. I'd better think of a possibility of destruction when it comes to SMAs!

And now I can understand why we need a model checker.. 😅

**Comment by poppindouble** [comment]
A little bit supplementary of https://github.com/kaist-cp/cs492-concur/issues/176#issuecomment-716957747, why thread clone can avoid use after free, hopes it helps :)

The source code of thread in Rust:

```
pub struct Thread {
    inner: Arc<Inner>,
}
```
By using the clone, we are actually increasing the counter and force the thread to live longer. So that's why in line 74 `thread.unpark();` we know that nodeB must be still available.
