### ISSUE TITLE
[Question] Question about the purpose of lock free data structures

### ISSUE THREAD

**Issue by travis1829** [kaist-cp/cs492-concur#184]
I understand that by using lock-free data structures, we can remove deadlock or livelock problems and also achieve better scalability. Especially, I thought better scalability was the main purpose to use such lock-free data structures.

However, in slide 84(https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.ga54eefc4bc_1_12), the professor explained scalability more like a side effect rather than the main purpose. Also, after googling about it, I found out that lock free data structures may be effective in situations with contentions, but it does not necessarily lead to better performance (or sometimes even worse) in average cases compared to lock-based methods, despite that it's much harder to implement.

Then, what can we say about the "main" purpose of using lock-free data structures?
That is, is solving deadlock, livelocks, or obtaining modularization the more bigger reason? Or, is it to achieve a data structure with a more stable performance? Or, does it highly depend on the circumstance?

I'm just curious about when lock-free data structures are necessary and when they are not.

**Comment by jeehoonkang** [comment]
- While I explained scalabililty is a "side" benefit, it's a huge benefit, still.

  Yes, indeed, with only a small number of cores, it's quite hard to beat lock-protected sequential data structures.  But there are advanced techinques (such as flat combining or helping) that improves the performance of lock-free data structures.  Unfortunately, probably we will not study those techniques in this semester.  If you're interested, I suggest you search for those terms.

  Also, with more than just a small number of cores, lock-free data structures usually beat sequential ones by large margin.  It's especially relevant to these days where typical CPUs have more than dozens of cores.  (Even datacenter CPUs have up to 64 cores and 128 hardware threads.)

- Guaranteeing progress, especially in the presence of such a large number of cores, is becoming more and more important problem.  We don't want to block the entire system, that may consists of hundreds of cores, due to a single "bad" thread that holds an important lock.

**Comment by travis1829** [comment]
I think I get what you mean. Also, it seems like both of them are really important reasons to use it! Thank you for answering!
