### ISSUE TITLE
[Question] Clarification on find method for Cursor

### ISSUE THREAD

**Issue by Lee-Janggun** [kaist-cp/cs492-concur#193]
1. The specification of `find` for `list_set::Cursor` says 'Move the cursor to the position of key in the sorted list.' However as we are working with a linked list, should we move the cursor when the key exists is a position later than the current node? For example if the key is `&3`, and the list list `3 -> 4 -> 5 -> 6`, but the cursor is at `5`, the current specification seems to require that we should return `true` and move the cursor to the first position, but it seems impossible to do so in a reasonable manner as we are working with a linked list.

2.  I am assuming that if there is no `key` in the linked list, we should not update the given Cursor at all. Is this right?

**Comment by tomtomjhj** [comment]
1. Please check the comment on the `Cursor` struct definition: https://github.com/kaist-cp/cs492-concur/blob/b004344d3d2cd4e1913a43e1bf9fa320f65e8878/homework/src/list_set.rs#L24
2. https://github.com/kaist-cp/cs492-concur/issues/187#issuecomment-719926209

**Comment by Lee-Janggun** [comment]
I just saw #187 and I think I have a better idea. What I don't get from the comment on the `Cursor` definition is what is `current node`? I honestly don't see the purpose of `Cursor` which is why I am confused about how to implement `find` and other related methods.

**Comment by tomtomjhj** [comment]
In your example (find 3 in `3 -> 4 -> 5 -> 6`), the "current node" would be 3 when `find` returns.

> I honestly don't see the purpose of Cursor

Yeah for this homework explicit cursor struct isn't that necessary because it's too simple. But in some complex search data structures it makes sense to make cursor type explicit. For example, the next lecture will cover lock-free list with slightly more complex cursor type.
https://github.com/kaist-cp/cs492-concur/blob/b004344d3d2cd4e1913a43e1bf9fa320f65e8878/lockfree/src/list.rs#L48-L51

**Comment by Lee-Janggun** [comment]
I think looking at the code you gave will help me understand more. Thank you!
