### ISSUE TITLE
[Question] HW#4 next function lock() problem

### ISSUE THREAD

**Issue by us0310306** [kaist-cp/cs492-concur#201]
I have problem that next() function of iter use lock() and it makes error.
So I made loop and used try_lock(), when get lock(), it breaks but it loop continuously.
I read #197 , but is it able to explain about it in detail?

**Comment by Jaegoomon** [comment]
I don't make sure that your problem is same as mine. But I think the main point is using `Option` type in `next()`. I had some problems about unnecessary blocking, because when I finished iter operation(get to null_ptr at iter), I didn't do anything and because of them, another iter can't do iter operation. So If your problem is related about it, 

1) check if you use lock uncorrectly(I mean your code make poisoned error or something)
2) by using `Option`, unlock the iter whose iteration was already finished

**Comment by us0310306** [comment]
Thank you for your answer!
But how can I know before iters when I reached at the end?
self will be `Some(mutexguard(ptr::null_mut()))` I think.
I have no idea about it....

**Comment by Lee-Janggun** [comment]
There is a very useful function [`ptr::is_null`](https://doc.rust-lang.org/beta/std/primitive.pointer.html#method.is_null) the checks if a raw pointer is null.

**Comment by us0310306** [comment]
Oh, I commented wrong I think.
I checked null and return None.
So how can I finish iter operation?

**Comment by Lee-Janggun** [comment]
If you did that you should be fine. The next function should not drop as the iterator can also be used again.

**Comment by us0310306** [comment]
Ok. Thank you for answer!!!
