### ISSUE TITLE
[Question] Lock-free linked list implementation questions

### ISSUE THREAD

**Issue by nv-quan** [kaist-cp/cs492-concur#209]
I have understood the concept of lock-free linked list. But I find that the implementation is quite hard to make sense of, even after watching the video. Here is some of them:
- In this line, why is next.with_tag(0) is used? If set it to 0, what if another thread perform an insert instruction into this node?
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L117
- Why self.prev is the same as self.curr here? Is this effectively ignore all the marked nodes?
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L124
- How can it delete the node if this code is just performing on the cursor? 
https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L138-L140

**Comment by jeehoonkang** [comment]
I hope this answers your questions.

- Regarding tagging 0 for `self.curr`: Here, you're not tagging the poitner in the shared memory with 0.  You're tagging your **local pointer** (`self.curr`) with 0.  It's necessary for L139 (https://github.com/kaist-cp/cs492-concur/blob/6c2658e043a1ba343853272013fb804ebdc4fc8f/lockfree/src/list.rs#L139), where the prev's next pointer is CAS'ed and the new pointer should be marked 0 because the prev is not logically deleted yet.

- Regarding ignoring the previously logically deleted nodes: Yes, you're right.  Harris's strategy doesn't physically delete earlier logically deleted nodes.  It physically deletes nodes only around the found node.

- Regarding deletion: the cursor is pointing to the shared memory, and the nodes in the shared memory are unlinked.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions.
