### ISSUE TITLE
[HW4] remove - how to take ownership partially?

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#211]
In `OrderedListSet<T>::remove` ,
we need to `free a node` and `return the data inside that node`.

To free the node, `drop(Box::from_raw(node_ptr))` is needed.
However, as we need to return the data inside that node,
it is necessary to take partial ownership of the data.

I tried various methods but it all fails to achieve the goal.

```
Method 1
{
let node = unsafe{Box::from_raw(node_ptr)};
let data = node.data;
return Ok(data)
}
```
`Problem : As **node**:Box<T> drops, all of its value in heap deallocated so **data** points to invalid address`

```
Method2
{
let data = unsafe{Box::from_raw(node_ptr)}.data;
return Ok(data)
}
```
`Problem: The node is not deallocated`

Is it possible to only take ownership partially??
The only possible way seems to be use `ptr::read` to make a bit-wise copy but it doesn't sound like good answer.
Any help will be greatly appreciated. Thanks.

**Comment by YujinGaya** [comment]
I believe you are practically bitwise copying the data into stack with both methods. That's the semantics of the *moving out of struct*. The box will be deallocated properly in both cases.

Do you have any evidence that there's a leak?

**Comment by AnHaechan** [comment]
1. Does the box get deallocated in `Method 2` also? Can you explain me the reason?

2. In `Method1`, when the node goes out of scope, the destructor of Box is called and doesn't it free all the memory it occupied?

**Comment by tomtomjhj** [comment]
I think both methods 1 and 2 are correct. Maybe something else is wrong.

**Comment by YujinGaya** [comment]
As you didn't elaborate your reasoning on why node won't be deallocated or provide evidence that there's a leak, I'll assume you thought a value that's not assigned to a variable won't be dropped.

```rust
fn main() {
    let data = vec![1, 3, 42][2];
    println!("{}", data);
}
```

If that's the case, above example would introduce a memory leak because `Vec` won't be dropped and deallocated.

To be precise there's a concept called [temporaries](https://doc.rust-lang.org/stable/reference/expressions.html#temporaries) which is exactly what we're concerning right now. A value that's not assigned to a variable is called a temporary and [it gets dropped at the end of enclosing statement](https://doc.rust-lang.org/stable/reference/destructors.html#temporary-scopes).


For the second question, following statement allocates `T` sized memory in the stack frame and copies the `data` from heap-allocated `Node` to the newly allocated area. When the `node` variable goes out of scope, it only calls `drop` for its fields other than data. In this case, next. This behavior is called _moving out of struct_ and it's only possible when the struct does not implement `Drop`, which is the case for `Node`

```rust
let data = node.data;
```

Here's an example slightly modified from https://github.com/kaist-cp/cs492-concur/issues/140#issuecomment-709664508. 

```rust
struct A(i32);

impl Drop for A {
    fn drop(self: &mut Self) {
        println!("A dropped");
    }
}

#[derive(Debug)]
struct B(i32);

impl Drop for B {
    fn drop(self: &mut Self) {
        println!("B dropped");
    }
}


struct Foo {
  a: A,
  b: B
}


fn main() {
  let foo = Box::new(Foo { a: A(1), b: B(42) });
  let b = foo.b; // heap allocated B(42) has been copied to a stack variable b
  println!("{:?}", b); // prints "B(42)"
  std::mem::forget(b);
} // prints "A dropped"
```

The analogy here is `Foo` corresponds to `Node`, and `b` corresponds to `data`. Note that `B` does not implement `Copy` even it's essentially a `i32`.

**Comment by AnHaechan** [comment]
Thanks for you kind explanation.
Can you tell me if I understood the concept correctly for the last time?
```
let foo = Box::new(Foo{a:A(1),b:B(3)});
```
``` 
[memory state]

Stack
|addr| --- foo
|       |
|       |

Heap
|       |
|A(1)| <--addr
|B(3)|
|       |
```

=>

```
let foo = Box::new(Foo{a:A(1),b:B(3)});
let b = foo.b;
```
``` 
[memory state]

Stack
|addr| --- foo
|       |
|B(3) | --- variable b

Heap
|       |
|A(1)| <--addr
|B(3)|
|       |
```

**Comment by YujinGaya** [comment]
Yes you're correct. In second picture, you cannot access b anymore as it has been already moved to the stack.
