### ISSUE TITLE
[Question] Invariant of CDS

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#231]
To guarantee the safety property of a CDS, we used release&acquire synchronization for some invariants.

For example, invariants of Michael-Scott's queue is 
` (1) release view of pointer ⊒ all messages of pointed node (2) tail is reachable from head`

I understand how the invariants are maintained and exploited via synchronization, 
but quite don't get **why/how these invariants are chosen**.

In what process the invariants are designed or selected?

**Comment by nv-quan** [comment]
The first invariant seems obvious because if it's not the case then it'll be really hard to predict all scenario.
The second invariant, in my opinion, is to guarantee that the tail will never get lost. For example when the queue is popped, if the invariant is not chosen, the memory location that the tail points to can be accidentally popped out, which will make the queue unusable. However I'm not sure if this is correct or not.

**Comment by jeehoonkang** [comment]
Invariants are by nature a guess.  Think of mathematical induction.  You pick the inductive invariant that manages to prove your final goal.  The same for concurrency.  You pick the synchronization invariant that manages to prove the safety of concurrent data structures.

The synchronization invariants are actually found quite recently.  Only after 2010 or so could we formally prove the safety of concurrent data structures.  Finding invariants and proving concurrent data structures is still an active area of research.  In my lab, we are working on proving concurrent garbage collectors.
