### ISSUE TITLE
[Question] [Homework 5] Bucket size and list count

### ISSUE THREAD

**Issue by haeeun-14** [kaist-cp/cs492-concur#239]
While doing the homework 5, there is a statement that I cannot understand. There is a comment:
```
impl<V> SplitOrderedList<V> {
    /// `size` is doubled when `count > size * LOAD_FACTOR`.
    const LOAD_FACTOR: usize = 2;
```
I know that the size should be increased when the count if doubled because the list need a new room(bit) to differentiate keys. However, while the paper uses a bucket list that is doubled every time there is a lack of bit number, our growable array increases its height. 
So I think the new size sould be `size << SEGMENT_LOGSIZE`, not `size<<1`. I am not sure whether I understand this correctly. Can you point out if I got it wrong?

**Comment by tomtomjhj** [comment]
The roll of `GrowableArray` is just to provide an array that can store at least `SplitOrderedList::size` pointers to buckets (sentinel nodes). Other than that, `SplitOrderedList` doesn't need to care about the internal details of `GrowableArray`. So I think `size << SEGMENT_LOGSIZE` won't break the functionality but it would be inefficient because bigger `size` ⇒ too many unnecessary sentinel nodes.
