### ISSUE TITLE
[Question][HW5] Growable array

### ISSUE THREAD

**Issue by zhanto97** [kaist-cp/cs492-concur#240]
Is there any particular reason why `root` of `GrowableArray` is initialized as `Atomic::null()`? Can I change it so that it is initialized as pointer to height 1 segment?

**Comment by tomtomjhj** [comment]
It's common practice not to allocate memory in `::new` functions to make the function [`const fn`](https://doc.rust-lang.org/reference/const_eval.html?highlight=const,fn#const-functions). But we didn't make it `const fn` because `const fn`-ness of `Atomic::null` wasn't available in stable rust (not sure why). Anyway, fill free to change the implementation of `GrowableArray::new`.
