### ISSUE TITLE
[Question] question about hazard pointers

### ISSUE THREAD

**Issue by jessi68** [kaist-cp/cs492-concur#248]
In the lecture of safe memory reclamation, I have a question that when we call
collect function? If one thread convert some block protected to unprotected, 
then always collection function is called? 
And I thought that array( index 0 represents head , ) as arr, arr[k] = 0 means k th  block is unprotected,
arr[k] = 1 means, kth block is protected. I thought when deciding whether this block is safe or not, hash table is
more efficient than linked list. ( and if we convert protected to unprotected, we just have to changing value ) 
So, why hazard pointer used linked list?

**Comment by tomtomjhj** [comment]
> when we call collect function?

Usually, `collect` is called in other SMR API function implementation. Example: crossbeam-epoch calls `collect` in `pin` (= `set_active`).
https://github.com/crossbeam-rs/crossbeam/blob/47110fd42d9b5d67548071e32714f39f59af642b/crossbeam-epoch/src/internal.rs#L498-L502

> hash table is more efficient than linked list [..] So, why hazard pointer used linked list?

Because it's relatively easy to implement lock-free set based on linked list. You can use any set data structures.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions.
