### ISSUE TITLE
[Question] AtomicUsize to Atomic<T>

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs492-concur#251]
> You'll need to perform some integer-pointer casts because `AtomicUsize` in Segment can be interpreted as both `Atomic<T>` and `Atomic<Segment>`. Use `into_usize` and `from_usize`.

This was in the description of HW5.

Ordinary conversion between `Atomic<T>` and `Shared<T>` is:
```
Atomic<T> =[ load(guard) ]=>  Shared<T>
```

However, when we convert `AtomicUsize` to `Shared<T>` like following:
```
AtomicUsize =[ load() ]=> usize =[ unsafe from_usize() ]=> Shared<T>
```

We've acquired `Shared<T>` **without guard**, and I think it is the exact 'unsafe' usage of `from_usize()` function.

So I've thought of 
```
AtomicUsize =[as Atomic<T>]=> Atomic<T> =[load(guard)]=> Shared<T>
```
but conversion `as` was only possible between primitive types.

How should I safely 'interpret' `AtomicUsize` as `Atomic<T>`?

**Comment by tomtomjhj** [comment]
> `AtomicUsize =[as Atomic<T>]=> Atomic<T> =[load(guard)]=> Shared<T>`
> but conversion as was only possible between primitive types.

Right. Note that `GrowableArray::get` returns `&Atomic<T>`, not `Atomic<T>`.
The pointer types can be cast to another pointer type using `as`: https://github.com/kaist-cp/cs492-concur/issues/225#issuecomment-727152497

**Comment by AnHaechan** [comment]
@tomtomjhj 
Thanks for your answer, 
but I was actually concerning about the CAS operation, rather than the return type.
At some point, we need to perform CAS on `Segement[inner][index] : AtomicUsize where index:  usize` .
Then, in this case, the same method can be applied ( typecasting the pointer and then perform CAS on that pointer ), right?

**Comment by tomtomjhj** [comment]
Yeah that is possible but there is another way to do this.
For example, let's say you want to make an empty slot point to a newly allocated segment. If you have `slot: &AtomicUsize`, `new: Owned<Segment>` there are two options for doing that:
1. casting `slot` to `&Atomic<Segment>` like #225 (but not `&Atomic<T>`) and `slot.compare_and_set(Shared::null(), ...)`
2. converting `new` to `usize`: `slot.compare_exchange(0, new.into_usize(), AcqRel, Acquire)`.

**Comment by AnHaechan** [comment]
@tomtomjhj 

But in the option **2.**, `guard` is not required.
Since slot is in fact, `Atomic<Segment>` which is shared,
is accessing it without `guard` safe?

**Comment by tomtomjhj** [comment]
`guard: &'g Guard` protects the memory block pointed to by a `Shared<'g, T>` from being reclaimed.  `guard` has nothing to do with the `slot` in this case because the memory block on which `slot` is placed will not be reclaimed.

Consider this example.
```rust
fn crossbeam_epoch_example() {
    let atomic: Atomic<i32> = Atomic::new(123);
    scope(|s| {
        for _ in 1..=2 {
            s.spawn(|_| {
                let atomic_ref: &Atomic<i32> = &atomic;
                let guard: Guard = pin();
                let shared: Shared<'_, i32> = atomic_ref.load(Acquire, &guard);
                if !shared.is_null() {
                    let reference: &i32 = unsafe { shared.deref() };
                    assert_eq!(*reference, 123);
                    if atomic_ref
                        .compare_and_set(shared, Shared::null(), Relaxed, &guard)
                        .is_ok()
                    {
                        unsafe { guard.defer_destroy(shared) };
                    }
                }
            });
        }
    })
    .unwrap();
}

```
`atomic` is a cell in the main thread's stack and it's initialized to a pointer to heap memory block containing `123`.
When a thread runs `load`, it copies the value of `atomic` and records it in the variable `shared`.
It's completely safe to access `atomic` via `atomic_ref`, because it lives on the main thread's stack.
Both thread can enter the first `if` block, with the same `shared` value.
Suppose thread 2 sleeps at this point and thread 1 keeps running.

If thread 1 runs `compare_and_set`, the value of `atomic` gets updated to`null`.
The value of `shared` doesn't change because it's just a snapshot of `atomic` at some moment.
Then thread 1 runs `defer_destroy(shared)` to request the reclamation of the heap memory block containing `123`.

Now the thread 2 wakes up and runs `shared.deref()` and read the `reference`.
This is safe because the heap memory block containing `123` is protected by the `guard` (`load`ed with `guard`).
`compare_and_set` will fail because the value of `atomic` is already `null`.

**Comment by integerblue** [comment]
> We've acquired Shared<T> without guard, and I think it is the exact 'unsafe' usage of from_usize() function.
@tomtomjhj So is this wrong?
Based on your explanation, I think the quoted sentence is wrong because the segments are not destroyed manually, but only after the whole GrowableArray is dropped. Therefore guard is not needed.

**Comment by tomtomjhj** [comment]
Yeah
