### ISSUE TITLE
[Question] michael-scott's queue tail ordering

### ISSUE THREAD

**Issue by wltn0029** [kaist-cp/cs492-concur#304]
In push() operation, I think ordering related to tail could be relaxed.
https://github.com/kaist-cp/cs492-concur/blob/master/lockfree/src/queue.rs#L81
https://github.com/kaist-cp/cs492-concur/blob/master/lockfree/src/queue.rs#L102-L104
Above lines are operation on tail with acquire-release synchronization. 

But I think those two operation can be implemented in relaxed ordering, because tail is always guaranteed to obtain latest knowledge on newly inserted node. Since tail only points to what is inserted newly by CAS on original node with release ordering, we don't need to double check node's latest information. 
```
head -> dummy -> node A -> node B -> null
                              ^
                             tail

                          (CAS : release / node B has latest value of node C)
head -> dummy -> node A -> node B -> node C -> null
                                       ^
                                     tail     <-- tail only points to the node C
                          
```
Since tail's compare_and_set doesn't need to be `release`, I think tail's load also doesn't need to be `acquire`.

**Comment by integerblue** [comment]
If you want to load the latest value of the tail pointer, you should load with acquire and compare_and_set with release.
If you do not use acquire in load operation, then previous information could be loaded, because that's what relaxed ordering is.

**Comment by wltn0029** [comment]
But I cannot find difference between treiber's stack pop operation.. Since stack's head load with acquire ordering, it use relaxed ordering when compare_and_set. I think inserting new node in tail should be implemented in acquire-release ordering (and my original question is wrong) but updating tail before inserting new node could be relaxed ordering. It is because node which becomes new tail is obtained acquire ordering.

I think this line could be relaxed : 
https://github.com/kaist-cp/cs492-concur/blob/master/lockfree/src/queue.rs#L91
because of this line : 
https://github.com/kaist-cp/cs492-concur/blob/master/lockfree/src/queue.rs#L85

**Comment by integerblue** [comment]
> Since stack's head load with acquire ordering, it use relaxed ordering when compare_and_set.
self.head is compare_and_set with release ordering in push(), so it is possible that head is loaded with acquire ordering.
If you want to use Acquire ordering, then you 'must' pair it with Release ordering. 
As we learned in promising semantics, if you want to acquire a view from another thread, then the thread should have released the view. Acquire or Release ordering alone cannot achieve getting the latest view.

**Comment by wltn0029** [comment]
Well,, now I understand why tail should have release-acquire synchronization. I think it is because tail is another commit point of queue, so it must obtain latest value of node. And it can be achieved by release ordering in compare_and_set operation. 
And stack's relaxed ordering in pop operation is slightly different because head is already acquired latest view of the node which becomes new head.
I wish I understand correctly.

**Comment by totolacky** [comment]
I'm not quite sure if your understanding is correct. For example,
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/list.rs#L231-L250
the 'tagging' CAS operation (line 236) in lock-free list is a commit point, but it is not synchronized with release/acquire.

**Comment by totolacky** [comment]
(Although I'm not sure if this understanding is correct) I think this would be a possible ordering criteria.
1. You use **acquire load** when you want to **exploit an invariant**. For example, for the **pointers** in the lock-free data structures we have learned, you use acquire load when you want to **dereference the pointer**.
2. You use **release store** when it is required to do so, in order to **maintain the invariants**.

Let's see the push() and pop() operations in Treiber's stack for an example.
https://github.com/kaist-cp/cs492-concur/blob/a9d355cf06323d33af17a9c22e57cb38fae37fe5/lockfree/src/stack.rs#L35-L84
**In push**
- We load `head` and `next` with relaxed ordering, because we do not intend to dereference them. (i.e. we do not need to exploit the invariant.)
- However, we store the `head` pointer with release ordering because according to the invariant, the `head pointer` must have a release view >= all other nodes' data & pointer messages. If we did not use release ordering here, the messages related to the new pointer `n` would not be covered by the release view of head.

**In pop**
 - We use acquire ordering for loading the `head` because we want to dereference the pointer in L66 (i.e. exploit the invariant).
 - Loading `next` is still relaxed as we are not intending to dereference it.
 - We store the `head` pointer with relaxed ordering, because according to the invariant, the previous release view is already covering the latest information of the remaining nodes' values and pointers. Therefore, we don't need to store with release ordering again.

I hope this helps.

**Comment by wltn0029** [comment]
I think your explanation is reasonable. 
So, I can conclude that the reason why compare_and_set operation on tail should be release is that tail view should be updated to the node which it hasn't had any information before.

**Comment by totolacky** [comment]
Yes, because the tail pointer does not naturally have the latest information about the next node's message. (And according to the invariant, the tail pointer's release view must have such information.)

**Comment by wltn0029** [comment]
It really helps me a lot :) Thanks everyone for answering my question!!

**Comment by integerblue** [comment]
@totolacky In your explanation, I have one question.
In pop(), self.head is compare_and_set with next value in relaxed ordering.
I understand that the new head is still ahead of other release views after the head, but it cannot be acquired by other thread's in push() self.head.load(Acquire) because it is not released with view.

**Comment by integerblue** [comment]
@totolacky @tomtomjhj 
self.head |0(released)|-|1(released)|-|2(released)|-|1(not released)|
in order push(0) push(1) push(2) pop(1)
how can we acquire the latest 1 with push(3) in acquire ordering?

**Comment by wltn0029** [comment]
oh sorry, i reopen the issue

**Comment by totolacky** [comment]
@integerblue That's a good point. My idea was that if an acquire load is done on a most-recently-non-released variable, then the latest released view is acquired. I actually considered three possible semantics for this, and they were
* Acquire the latest release view.
* Do not acquire anything. Just do the same thing as relaxed load.
* Panic.

The first option seemed most likely. However, it is just my guess so it would be best to get an explanation from @tomtomjhj and @jeehoonkang!

**Comment by integerblue** [comment]
@totolacky What I think if the answer is the first option, in pop(), the latest view which is 2 which is already popped is acquired so that CAS is repeatedly failed in loop because 2(released) is already CASed with 1(not released).

**Comment by tomtomjhj** [comment]
> And stack's relaxed ordering in pop operation is slightly different because head is already acquired latest view of the node which becomes new head.

right

**Comment by totolacky** [comment]
@integerblue That would be problematic.

**Comment by Lee-Janggun** [comment]
> how can we acquire the latest 1 with push(3) in acquire ordering even if it is not released?

I'm not sure if this is possible. I'm not sure I understand your question fully, but I think you are trying to consider when by 2 is poped from the stack, but the thread that is trying to insert 3 does not see it's view. I think the key part that does not allow this is that when the removal of 1 happens, it is done by a CAS, which is an atomic operation, so the fact that `self.head` is updated to 1 is appended right next to `self.head`'s current view. If we were working with MS queue, this would not be enough because the fact that `tail`'s view is atomically updated is not sent to the `head`'s view. But as we are only working with `head` view, if we update it with a CAS, it is ok.

This then raises the question why do we need to `Release` in `push`. I think this is related to the invariant. For `pop`, as we have atomically updated the heads view from its current acquired view, the view of the other nodes will still be included in the new heads view. I think you can think of this as the view of the head nudged slightly to the right in the promising semantics diagrams. 

For `push`, the head is updated to a new node which we do not have any information on the view. Thus to maintain the invariant, we must update the most recent view with `Release`.
