### ISSUE TITLE
[Question] Homework6 get_protected_collect_sync synchronization

### ISSUE THREAD

**Issue by j2k0618** [kaist-cp/cs492-concur#323]
I passed all the other test cases but I cannot pass below assertion case and failed in get_protected_collect_sync.
```Rust
if !shield.is_null() {
    // safe to deref a valid pointer via a validated shield
    !(unsafe { *shield.deref() }, 123);   <==== here
}
```
If I don't retire and collect in that test case, it passed so I think there is a problem in fence of get_protected function.
I put fence after making the shield and validate it to loop to make the proper shield in get_protected function.
I also tried making fence before returning the shield but It failed.
Is this not enough for synchronization?

**Comment by hoyacj1** [comment]
I had a similar problem, but I'm not sure that the reason of that is same.
When we validate(after making the shield), we should load shared pointer **again**, from given atomic pointer.
I found that I didn't do like that, and I solve the problem by fixing it.
I hope that it is helpful for you :)

**Comment by tomtomjhj** [comment]
`get_protected` doesn't need a fence itself if `protect` is correct.

**Comment by j2k0618** [comment]
Thank you!
@tomtomjhj Since I passed protect_collect_sync test, I think my protect is correct.
My protect get current id and get local hazards from HAZARDS to make shield with it.
Then, make a fence and return.
In retire, after I push pointers into vector, make a fence.
I think there may be problems in the other functions...

@hoyacj1 Why should we load shared pointer again after making the shield? Could you explain it with more details? I already load the shared pointer again for each loop if I fail the validation. Thank you!

**Comment by tomtomjhj** [comment]
can you try this? https://github.com/kaist-cp/cs492-concur/issues/319#issuecomment-748584977 


btw
> In retire, after I push pointers into vector, make a fence.

it's more efficient to issue a fence at the start of `collect`.

**Comment by hoyacj1** [comment]
@j2k0618  Because the inside of atomic pointer can be changed before validate. 
Suppose the atomic pointer 'a' contains shared pointer `shared_a`, and we load it and made a shield with it.

`
|a| --> shared_a
`

While making shield, the atomic pointer's inner value can be changed to `shared_b` by another threads.

`
shared_b <-- |a|       shared_a         
`

If we don't load again after making shield, the validate function compares **input shared pointer** `shared_a`(which is **not reachable** from atomic pointer) and **shared pointer protected by the shield**, `shared_a`. Although the real inner value of atomic pointer `a` is `shared_b`, validate should be succeed and the result of get_protected is shield of `shared_a`. It is invalid situation.
