### ISSUE TITLE
[Homework 1] hello_server (due: 2020-09-25T23:59:59+0900)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs492-concur#49]
Implement a parallel web server with cache.

- Read [this manual](https://github.com/kaist-cp/cs492-concur/blob/master/homework/README.md) for general advice on homework.

- Watch [this video](https://www.youtube.com/watch?v=wQeUKeSYFzM) for specification.

- Use [skeleton code](https://github.com/kaist-cp/cs492-concur/tree/master/homework/src/hello_server) as a starting point, and fill out `todo!()`.
    + **IMPORTANT**: don't fork this repository.  It'll be public!

- Submit your code [here](https://gg.kaist.ac.kr/assignment/18/).

- **IMPORTANT**: only the last submission counts.  Please make sure the last line of the "log" says "Score: ?? / 100".

- The grader runs `./script/grade-1.sh` in the `homework` directory.  If the server's evaluation results differ from your own evaluation results, please let me know.

**Comment by nv-quan** [comment]
Do we have to write the `src/bin/hello_server.rs` ?

**Comment by tomtomjhj** [comment]
## Reading Rust book
This homework requires a good understanding of materials covered in Rust book §20. This is the minimal path for understanding §20: §1, 2, 3, 4, 5, 6, 8, 9, 10, 13.1, 13.2, **15**, **16**, **20**.

Specifically, make sure that you understand following topics.
* [`Drop`](https://doc.rust-lang.org/std/ops/trait.Drop.html) trait and [`drop`](https://doc.rust-lang.org/std/mem/fn.drop.html) function
* Type signature of [`std::thread::spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html) and the meaning of [`std::thread::JoinHandle`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html).
* The meaning and usage of [`Arc<`](https://doc.rust-lang.org/std/sync/struct.Arc.html)[`Mutex<T>>`](https://doc.rust-lang.org/std/sync/struct.Mutex.html).
* [Channels](https://doc.rust-lang.org/std/sync/mpsc/index.html).


## Major differences between HW1 and Rust book §20
* We use [`crossbeam_channel`](https://docs.rs/crossbeam-channel/) instead of [`std::sync::mpsc`](https://doc.rust-lang.org/std/sync/mpsc/index.html). Since crossbeam channel is mpmc, you don't need to wrap the `Receiver` inside a `Mutex`.
* We do not use explicit exit message for thread pool. Instead, we disconnect the channel by `drop`ping the receiver/sender.
    * The message type is simply defined as:
      ```rust
      struct Job(Box<dyn FnOnce() + Send + 'static>);

      ```
    * Each worker thread automatically breaks out of the loop if the channel is disconnected.
* We `join()` each thread in the destructor of `Worker`, not in the destructor of `ThreadPool`. Since `ThreadPool` has field `workers: Vec<Worker>`, the worker destructor will be called when the pool is dropped. Note that the channel should be disconnected before `join()`ning the worker threads. (Otherwise, `join` will block.) This means that the `Sender` should be dropped before `Vec<Worker>`. You can specify the drop order in many ways. In this homework, we use `ThreadPool::job_sender` of type `Option<Sender<Job>>`, content of which can be `take()`n and `drop()`ped explicitly in `<ThreadPool as Drop>::drop`.

## Tips for implementing each extension
* Cache: Start with `Mutex<HashMap<K, V>>`. To fully implement the specification, you will need a more complicated type.
* Interrupt handler: just follow the comments.
* Thread pool: Ignore `ThreadPoolInner` first (used for `ThreadPool::join`), and implement the changes discussed in the previous section.

**Comment by tomtomjhj** [comment]
## Testing
I just added some tests for homework 1. To run the tests, run
```
cargo test hello_server
```
We will use those tests for grading, too. We may add some more tests for grading, but if your solution passes all the given tests, it's very likely that you will get the full score.

Also try running tests with the [LLVM sanitizers](https://github.com/kaist-cp/cs492-concur/tree/master/homework#using-llvm-sanitizers) enabled. They are not that useful for HW1 (unless you used unsafe features) but they will be very helpful for upcoming homeworks.

## Some changes in the specification
See <https://github.com/kaist-cp/cs492-concur/commit/85722fd5f1a5e5383e370e7feeebbb91192aff35#diff-1db87cfba2d093beedfd2fcf93408fefR20-R21>.  This change is for [this test function](https://github.com/kaist-cp/cs492-concur/blob/36e06f05caac461974a216a7e377b001ee3de44b/homework/src/hello_server/thread_pool.rs#L153).  If you're already running `.join().unwrap()` on the thread join handle, you probably won't need to fix your code.

**Comment by tomtomjhj** [comment]
**Update**: https://github.com/kaist-cp/cs492-concur/commit/465f150f30f2e07ea8abbec6fa113573be5abd96 Use [barriers](https://doc.rust-lang.org/std/sync/struct.Barrier.html) in cache test.

**Comment by tomtomjhj** [comment]
**Update**: https://github.com/kaist-cp/cs492-concur/commit/0f3d7e1497f5ec80a0d851e08801cc82a776b9fe some more comments in thread_pool.rs.

Some students said `thread_pool_drop_propagate_panic` test hangs. If this test hangs, you're probably doing something unnecessary in `<ThreadPool as Drop>::drop`. The lastest commit may help you to understand the problem.

**Comment by integerblue** [comment]
To run the sanitizer code, I had to run the following command in a git issue:

https://github.com/emosenkis/esp-rs/issues/10#issue-343649516

> ## Testing
> I just added some tests for homework 1. To run the tests, run
> 
> ```
> cargo test hello_server
> ```
> 
> We will use those tests for grading, too. We may add some more tests for grading, but if your solution passes all the given tests, it's very likely that you will get the full score.
> 
> Also try running tests with the [LLVM sanitizers](https://github.com/kaist-cp/cs492-concur/tree/master/homework#using-llvm-sanitizers) enabled.
> 
> ```
> RUSTFLAGS="-Z sanitizer=address" cargo +nightly test hello_server --target x86_64-unknown-linux-gnu
> TSAN_OPTIONS="suppressions=suppress_tsan.txt" RUST_TEST_THREADS=1 RUSTFLAGS="-Z sanitizer=thread" cargo +nightly test hello_server --target x86_64-unknown-linux-gnu
> ```
> 
> They are not that useful for HW1 but they will be very helpful for upcoming homeworks.
> 
> ## Some changes in the specification
> See [85722fd#diff-1db87cfba2d093beedfd2fcf93408fefR20-R21](https://github.com/kaist-cp/cs492-concur/commit/85722fd5f1a5e5383e370e7feeebbb91192aff35#diff-1db87cfba2d093beedfd2fcf93408fefR20-R21). This change is for [this test function](https://github.com/kaist-cp/cs492-concur/blob/36e06f05caac461974a216a7e377b001ee3de44b/homework/src/hello_server/thread_pool.rs#L153). If you're already running `.join().unwrap()` on the thread join handle, you probably won't need to fix your code.

**Comment by jeehoonkang** [comment]
Just FYI: I'll upload instructions for uploading your solution.  If the test above works, you'll get the full credits.

**Comment by jeehoonkang** [comment]
- You can evaluate your solution by running './script/grade-1.sh` in the `homework` directory.  Please merge the upstream changes.
- https://gg.kaist.ac.kr will soon accept your solution.  If its results differ from your own evaluation results, please let me know.

**Comment by integerblue** [comment]
My code passes "cargo test hello_server" command, but it fails with "./scripts/grade-1.sh" in
Test failed:    cargo_tsan test hello_server::thread_pool::test::thread_pool_join_block 

What would be the reason for this?

**Comment by YujinGaya** [comment]
For those who did the homework with their own mac and struggling to execute the test script like what I just did:

It doesn't work on macOS because mac doesn't ship `timeout` command.
You can either install the utility with [homebrew](https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x/21118126) or use this course's linux machine, and I chose the latter.

**Comment by tomtomjhj** [comment]
@integerblue Can you make a new issue with output from this command?
```sh
source ./scripts/grade-utils.sh
cargo_tsan test hello_server::thread_pool::test::thread_pool_join_block
```

**Comment by hestati63** [comment]
The current grader accepts the code even if the tests are failed.

**Comment by hestati63** [comment]
The current grader marks the submission as successful even if the test is failed.

Also, my machine displays the error message:
```bash
./scripts/grade-1.sh: line 64: [: too many arguments.
```

**Comment by jeehoonkang** [comment]
To all: please submit your solution as instructed in the issue.

@hestati63 

- gg is fixed.  Please resubmit your solution.
- for this semester, please look at the last line of the log to know your score.  sorry for the inconvenience.

**Comment by nv-quan** [comment]
I think the timeout should be bigger or something should be changed in the grader, I have no issue running each individual command (cargo, cargo_asan, cargo_tsan), except that it always need to recompile and build, which takes time, hence timeout for the test at the grader. To be clear after building the test run in next to no time, so it's not because of my code.

**Comment by tomtomjhj** [comment]
@nv-quan Sorry, there was a mistake in grader script: https://github.com/kaist-cp/cs492-concur/commit/23acd8093caa0708f765f2f4a9f20b2956cafb95 (`cargo build` doesn't build tests)

**Comment by nv-quan** [comment]
> @nv-quan Sorry, there was a mistake in grader script: [23acd80](https://github.com/kaist-cp/cs492-concur/commit/23acd8093caa0708f765f2f4a9f20b2956cafb95) (`cargo build` doesn't build tests)

Thanks, it runs ok in my machine now. But when I tried the grader before  [23acd80](https://github.com/kaist-cp/cs492-concur/commit/23acd8093caa0708f765f2f4a9f20b2956cafb95) in the server it still run well.

**Comment by haeeun-14** [comment]
The command
`./scripts/submit.sh
ls ./target/hw1.zip # ~~`
only made a new zip file, not submitted. Can you explain how it works in detail please?

**Comment by YujinGaya** [comment]
> The command
> `./scripts/submit.sh ls ./target/hw1.zip # ~~`
> only made a new zip file, not submitted. Can you explain how it works in detail please?

You can just submit the file to [the form here](https://gg.kaist.ac.kr/assignment/18/). I thought the name `submit.sh` is a little misleading too.

**Comment by Rainhunter13** [comment]
Is there a late submission? TT

**Comment by jeehoonkang** [comment]
**IMPORTANT**

- It seems many students didn't submit their solutions for hw1, and the average score for hw1 is much lower than I expected.

- I'll create a new (nominal) homework "hw1-late" that will be due in two weeks (9th of October).  Your final score for each module of hw1 is the maximum of the hw1 score and R * hw1-late score, where "R" will be announced later.
    + If you got 40 pts for hw1 threadpool and didn't submit for hw1-late, your final score for threadpool is 40 pts.
    + If you got 30 pts for hw1 threadpool and 40 pts for hw1-late threadpool, your final score for threadpool is max(30, 40R).

- There will be no more late submissions from hw2 and on.  If it's too harsh, please **raise an issue ASAP** so that I can handle it in a timely manner and there'll be no fairness issues.

**Comment by jeehoonkang** [comment]
Please submit your late submission for homework 1 by 23:59:59, 9th of October to https://gg.kaist.ac.kr/assignment/20/ .
