### ISSUE TITLE
[Question] Rust book questions regarding paths 

### ISSUE THREAD

**Issue by kyungyunlee** [kaist-cp/cs492-concur#60]
I have 2 questions when reading the book's chapter 7.4 "Bringing Paths into Scope with the use Keyword"

1. 
Here, the code imports `HashMap` from `std` library and initiate a hash map by stating `HashMap::new()`, which makes sense. 
```
use std::collections::HashMap;

fn main() {
    let mut map = HashMap::new();
    map.insert(1, 2);
}
```

However, in the following example, the code imports `Rng` , but call `rand::thread_rng()` instead. 
I thought it would make more sense to start with `Rng`... 
Could you explain why the syntax is like this for this library?  
Maybe I have been missing something from the book.

```
use rand::Rng;

fn main() {
    let secret_number = rand::thread_rng().gen_range(1, 101);
}
```

2. 
What is the purpose of  the brackets in `io::Result<()>`?  

```
use std::fmt;
use std::io;

fn function1() -> fmt::Result {
    // --snip--
}

fn function2() -> io::Result<()> {
    // --snip--
}
```
Thank you!

**Comment by tomtomjhj** [comment]
## 1
`path::identifier` refers to the `indentifier` under `path`.
(`indentifier` itself can be a part of path.)

`use path::identifier` allows you to use `identifier` without specifying the full path.
After `use std::collections::HashMap;`, you can use `HashMap` without specifying `std::collections::`.

So `Hashmap::new` refers to [this function (associated with the struct `Hashmap`)](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.new), and `rand::thread_rng` refers to [this function](https://docs.rs/rand/0.7.3/rand/fn.thread_rng.html).
`Rng::thread_rng()` is invalid because `thread_rng` doesn't belong to `rand::Rng`. So this is not the problem of syntax, but of module structure.

Note that identifiers `std` and `rand` are already known. This is because they are crate (≈ package) names whose identities are provided by the build tool (or whatever).

## 2
`<>` provides arguments to genetic types.

* `std::result::Result` is a generic type that accepts 2 type parameters. https://doc.rust-lang.org/std/result/enum.Result.html. Since this type is very frequently used, it is `use`d by default. So you can simply write `Result` without specifying the full path.
* `std::fmt::Result` is a type alias that instantiates `std::result::Result` with `()` and `std::fmt::Error`. <https://doc.rust-lang.org/std/fmt/type.Result.html>
* `std::io::Result` is a generic type alias that accepts has one parameter `T` and instantiates `std::result::Result` with `T` and `std::io::Error`. https://doc.rust-lang.org/std/io/type.Result.html

**Comment by YujinGaya** [comment]
1. 

`rand` is in the scope because it is name of the crate, hence you can `use rand::Rng`. You use Rng because it is a trait (which is covered in section 10.2 of same book) that needs to be in the scope when you want to call `gen_range`.

What happens in the code is `rand::thread_rng()` return [ThreadRng](https://rust-random.github.io/rand/rand/rngs/struct.ThreadRng.html) struct. Then, `ThreadRng` implements [Rng](https://rust-random.github.io/rand/rand/trait.Rng.html) trait and the trait has [gen_range](https://docs.rs/rand/0.7.3/rand/trait.Rng.html#method.gen_range) method. If you want to call a method from a trait, the trait should be in the scope of calling the method.

2.

`Type1<Type2>` is the syntax of `generics` and it will be covered in 10.1. `()` is the only value of [unit type](https://doc.rust-lang.org/std/primitive.unit.html).

**Comment by tomtomjhj** [comment]
Closing. Please feel free to reopen it if you have follow-up questions.
