### ISSUE TITLE
What is the difference between 4 ideas of promising semantics?

### ISSUE THREAD

**Issue by integerblue** [kaist-cp/cs492-concur#92]
I am really confused between the 3 ideas of promising semantics covered by today's lecture.
It seems that all those ideas are closely related and the #3 semantic view covers what is covered by 1 and 2. 
Is 'view' a developed semantics which could cover coherence and synchronization?

Also, why message adjacency is important if later write to memory should be later than the old value?
Furthermore, It is not straightforward why timestamps are required. An array seems to be enough because length does not do anything here.

It would be nice if you could elaborate more on how those semantic ideas differ and related to each other.

**Comment by YujinGaya** [comment]
From what I understand, they're four rules of one model called _promising semantics_. And it's a model that helps us understand how a concurrent program can be reordered or interleaved.

Message adjacency is about how the promising semantics model read-modify-write operations while WW coherence has nothing to do with the operation.

When we think of read-modify-writes, there are two threads sharing a resource, in this case a counter, that can freely interleaved. Message adjacency explains why using the read-modify-write operation prevents race condition. Because read-modify-write can only write a message adjacent to the old one and no two messages can be adjacent to the same old message.

When we talk about WW coherence, it's per-thread. That is, from one thread's perspective, two writes to a resource (regardless of whether it's shared or not) should be ordered along with the code's order of those two writes.

About the timestamp, it's just a mental model so it's not important how it can be implemented as it will never be.

**Comment by jeehoonkang** [comment]
> From what I understand, they're four rules of one model called _promising semantics_. And it's a model that helps us understand how a concurrent program can be reordered or interleaved.

Yes, it correctly captures the relationships between the four ideas.  (1) The interleaving of thread executions is the basic/unavoidable nondeterminism arising from concurrency.  (2) We can tame the nondeterminism due to interleaving by using RMWs.  (3,4) The semantics is relaxed due to intra-thread reorderings, which is described by views and promises.  We can tame relaxedness by access ordering or fence.


> When we think of read-modify-writes, there are two threads sharing a resource, in this case a counter, that can be freely interleaved. Message adjacency explains why using read-modify-write operations prevents race condition. The counter's value is 2 instead of 1 because read-modify-write can only write a message adjacent to the old one and no two messages can be adjacent to the same old message.

That's right.


> About the timestamp, it's just a mental model so it's not important how it can be implemented as it will never be.

To elaborate a little bit more about timestamp, we need to allow a thread to writes a message **before** the latest message.  In other words, we need to be able to "split" the memory for a location and insert a new message in-between.  That's the reason we use a map from timestamp to message, rather than an array of messages.

**Comment by YujinGaya** [comment]
I, somewhat arrogantly, said that it's just a mental model and there won't be an implementation. Today I skimmed professor Kang's original [paper on promising semantics](https://sf.snu.ac.kr/promise-concurrency/) and it seems like there is [an actual implementation](https://github.com/snu-sf/promising-coq).

> In §5, we present our formal results—validating many program transformations, compilation to x86-TSO and Power, DRF theorems, and an invariant-based logic—most of which are fully mechanized in the Coq proof assistant (totalling about 30K lines of Coq)

I looked at the source code of the proof assistant and I could find actual definition of the [message](https://github.com/snu-sf/promising-coq/blob/master/src/lang/Cell.v#L20-L26), and Cell below that seems like those multi-valued memory we talked about in the class as it has DenseOrderMap with pairs of DenseOrder and Message? I don't know how coq works but at least I wanted to confess that I made a mistake. Sorry for giving you misconception @integerblue.

**Comment by jeehoonkang** [comment]
> Today I skimmed professor Kang's original [paper on promising semantics](https://sf.snu.ac.kr/promise-concurrency/)

What?  Why...?

More seriously, I don't think we can regard the formalization in Coq as an implementation.  An implementation means an efficiently computable machine, e.g., x86 or ARM machines.  Promising semantics doesn't have such a machine; it's a mathematical model, but it's proven that the compilation to x86/ARM/Power is sound.

**Comment by YujinGaya** [comment]
> What? Why...?

Because there was a link to the paper in README

Thank you for the clarification. Since it's called *proof assistant* I had a feeling that it's only used to prove the soundness of the semantics and it's not a working implementation of a full language, but getting confirmed by the author made it all clear!
